// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_dout,
        data_V_empty_n,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_pp0_stage1 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [911:0] data_V_dout;
input   data_V_empty_n;
output   data_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_read;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;
reg[15:0] ap_return_16;
reg[15:0] ap_return_17;
reg[15:0] ap_return_18;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln36_fu_268_p2;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
reg   [0:0] ap_phi_mux_do_init_phi_fu_191_p6;
reg    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state7_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
reg    data_V_blk_n;
wire    ap_block_pp0_stage1;
reg   [0:0] do_init_reg_186;
reg   [911:0] data_V_load_rewind_reg_203;
reg   [5:0] i_part_0_i_i79_reg_218;
reg   [911:0] data_V_load_phi_reg_233;
reg   [9:0] p_05_i_idx_i78_reg_245;
reg   [0:0] icmp_ln36_reg_1147;
reg   [0:0] icmp_ln36_reg_1147_pp0_iter1_reg;
wire   [5:0] i_part_fu_278_p2;
reg   [5:0] i_part_reg_1151;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] grp_fill_buffer_fu_259_ap_return;
reg  signed [15:0] data_buf_V_0_0_i_reg_1156;
wire  signed [24:0] sext_ln1118_1_fu_289_p1;
reg  signed [24:0] sext_ln1118_1_reg_1165;
wire  signed [25:0] sext_ln1118_2_fu_292_p1;
reg  signed [25:0] sext_ln1118_2_reg_1170;
reg   [15:0] trunc_ln_reg_1176;
reg   [15:0] acc_0_1_V_reg_1182;
reg   [14:0] trunc_ln708_2_reg_1188;
reg   [15:0] acc_0_3_V_reg_1193;
reg   [15:0] acc_0_4_V_reg_1199;
wire   [9:0] add_ln96_fu_489_p2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_state1;
reg    grp_fill_buffer_fu_259_ap_ce;
wire    ap_block_state2_pp0_stage0_iter0_ignore_call23;
wire    ap_block_state4_pp0_stage0_iter1_ignore_call23;
wire    ap_block_state6_pp0_stage0_iter2_ignore_call23;
reg    ap_block_pp0_stage0_11001_ignoreCallOp41;
reg    ap_block_state3_pp0_stage1_iter0_ignore_call23;
wire    ap_block_state5_pp0_stage1_iter1_ignore_call23;
wire    ap_block_state7_pp0_stage1_iter2_ignore_call23;
reg    ap_block_pp0_stage1_11001_ignoreCallOp43;
reg   [911:0] ap_phi_mux_data_V_load_rewind_phi_fu_207_p6;
reg   [5:0] ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6;
wire   [911:0] ap_phi_reg_pp0_iter0_data_V_load_phi_reg_233;
reg   [911:0] ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233;
wire    ap_block_pp0_stage0;
reg   [15:0] res_6_V_0374_fu_100;
wire   [15:0] res_6_V_1_fu_741_p3;
reg   [15:0] res_5_V_0368_fu_104;
wire   [15:0] res_5_V_1_fu_725_p3;
reg   [15:0] res_7_V_03510_fu_108;
wire   [15:0] res_7_V_1_fu_709_p3;
reg   [15:0] res_8_V_03416_fu_112;
wire   [15:0] res_8_V_1_fu_693_p3;
reg   [15:0] res_4_V_03320_fu_116;
wire   [15:0] res_4_V_1_fu_677_p3;
reg   [15:0] res_9_V_03222_fu_120;
wire   [15:0] res_9_V_1_fu_662_p3;
reg   [15:0] res_10_V_03128_fu_124;
wire   [15:0] res_10_V_1_fu_522_p3;
reg   [15:0] res_3_V_03032_fu_128;
wire   [15:0] res_3_V_1_fu_646_p3;
reg   [15:0] res_11_V_02934_fu_132;
wire   [15:0] res_11_V_1_fu_562_p3;
reg   [15:0] res_12_V_02840_fu_136;
wire   [15:0] res_12_V_1_fu_631_p3;
reg   [15:0] res_2_V_02744_fu_140;
wire   [15:0] res_2_V_1_fu_623_p3;
reg   [15:0] res_13_V_02646_fu_144;
wire   [15:0] res_13_V_1_fu_608_p3;
reg   [15:0] res_14_V_02552_fu_148;
wire   [15:0] res_14_V_1_fu_601_p3;
reg   [15:0] res_1_V_02456_fu_152;
wire   [15:0] res_1_V_1_fu_554_p3;
reg   [15:0] res_15_V_02358_fu_156;
wire   [15:0] res_15_V_1_fu_593_p3;
reg   [15:0] res_16_V_02264_fu_160;
wire   [15:0] res_16_V_1_fu_585_p3;
reg   [15:0] res_0_V_02168_fu_164;
wire   [15:0] res_0_V_1_fu_514_p3;
reg   [15:0] res_17_V_02070_fu_168;
wire   [15:0] res_17_V_1_fu_577_p3;
reg   [15:0] res_18_V_01976_fu_172;
wire   [15:0] res_18_V_1_fu_569_p3;
reg   [15:0] data_buf_V_0_0_06281_i77_fu_176;
wire  signed [25:0] mul_ln1118_fu_962_p2;
wire  signed [25:0] mul_ln1118_1_fu_969_p2;
wire  signed [24:0] mul_ln1118_2_fu_976_p2;
wire  signed [25:0] mul_ln1118_3_fu_983_p2;
wire  signed [25:0] mul_ln1118_4_fu_990_p2;
wire  signed [25:0] mul_ln1118_5_fu_997_p2;
wire  signed [21:0] mul_ln1118_6_fu_1003_p2;
wire   [11:0] trunc_ln708_6_fu_412_p4;
wire  signed [24:0] mul_ln1118_7_fu_1010_p2;
wire   [14:0] trunc_ln708_7_fu_425_p4;
wire  signed [25:0] mul_ln1118_8_fu_1016_p2;
wire   [23:0] shl_ln_fu_447_p3;
wire   [16:0] shl_ln1118_1_fu_458_p3;
wire  signed [24:0] sext_ln1118_4_fu_465_p1;
wire  signed [24:0] sext_ln1118_3_fu_454_p1;
wire   [24:0] add_ln1118_fu_469_p2;
wire   [14:0] trunc_ln708_9_fu_475_p4;
wire   [0:0] icmp_ln203_2_fu_495_p2;
wire   [0:0] icmp_ln203_3_fu_501_p2;
wire   [15:0] select_ln203_9_fu_507_p3;
wire   [9:0] p_05_i_idx1_14_t_i_fu_529_p2;
wire   [0:0] icmp_ln203_fu_535_p2;
wire   [0:0] icmp_ln203_1_fu_548_p2;
wire   [15:0] select_ln203_fu_541_p3;
wire   [15:0] acc_0_8_V_fu_438_p4;
wire  signed [15:0] acc_0_7_V_fu_434_p1;
wire  signed [15:0] acc_0_6_V_fu_421_p1;
wire   [15:0] acc_0_5_V_fu_403_p4;
wire  signed [15:0] acc_0_2_V_fu_400_p1;
wire   [15:0] select_ln203_1_fu_615_p3;
wire   [15:0] select_ln203_2_fu_639_p3;
wire  signed [15:0] acc_0_9_V_fu_485_p1;
wire   [15:0] select_ln203_3_fu_654_p3;
wire   [15:0] select_ln203_4_fu_670_p3;
wire   [15:0] select_ln203_5_fu_685_p3;
wire   [15:0] select_ln203_6_fu_701_p3;
wire   [15:0] select_ln203_7_fu_717_p3;
wire   [15:0] select_ln203_8_fu_733_p3;
wire  signed [15:0] mul_ln1118_fu_962_p0;
wire  signed [9:0] mul_ln1118_fu_962_p1;
wire  signed [15:0] mul_ln1118_1_fu_969_p0;
wire   [10:0] mul_ln1118_1_fu_969_p1;
wire   [8:0] mul_ln1118_2_fu_976_p1;
wire  signed [15:0] mul_ln1118_3_fu_983_p0;
wire  signed [10:0] mul_ln1118_3_fu_983_p1;
wire  signed [15:0] mul_ln1118_4_fu_990_p0;
wire  signed [10:0] mul_ln1118_4_fu_990_p1;
wire  signed [15:0] mul_ln1118_5_fu_997_p0;
wire   [9:0] mul_ln1118_5_fu_997_p1;
wire   [5:0] mul_ln1118_6_fu_1003_p1;
wire  signed [15:0] mul_ln1118_7_fu_1010_p0;
wire   [8:0] mul_ln1118_7_fu_1010_p1;
wire  signed [15:0] mul_ln1118_8_fu_1016_p0;
wire  signed [9:0] mul_ln1118_8_fu_1016_p1;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [15:0] ap_return_5_preg;
reg   [15:0] ap_return_6_preg;
reg   [15:0] ap_return_7_preg;
reg   [15:0] ap_return_8_preg;
reg   [15:0] ap_return_9_preg;
reg   [15:0] ap_return_10_preg;
reg   [15:0] ap_return_11_preg;
reg   [15:0] ap_return_12_preg;
reg   [15:0] ap_return_13_preg;
reg   [15:0] ap_return_14_preg;
reg   [15:0] ap_return_15_preg;
reg   [15:0] ap_return_16_preg;
reg   [15:0] ap_return_17_preg;
reg   [15:0] ap_return_18_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_174;
reg    ap_condition_52;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
#0 ap_return_5_preg = 16'd0;
#0 ap_return_6_preg = 16'd0;
#0 ap_return_7_preg = 16'd0;
#0 ap_return_8_preg = 16'd0;
#0 ap_return_9_preg = 16'd0;
#0 ap_return_10_preg = 16'd0;
#0 ap_return_11_preg = 16'd0;
#0 ap_return_12_preg = 16'd0;
#0 ap_return_13_preg = 16'd0;
#0 ap_return_14_preg = 16'd0;
#0 ap_return_15_preg = 16'd0;
#0 ap_return_16_preg = 16'd0;
#0 ap_return_17_preg = 16'd0;
#0 ap_return_18_preg = 16'd0;
end

fill_buffer grp_fill_buffer_fu_259(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_V_read(ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233),
    .p_read1(data_buf_V_0_0_06281_i77_fu_176),
    .partition(i_part_0_i_i79_reg_218),
    .ap_return(grp_fill_buffer_fu_259_ap_return),
    .ap_ce(grp_fill_buffer_fu_259_ap_ce)
);

myproject_mul_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_10s_26_1_1_U7(
    .din0(mul_ln1118_fu_962_p0),
    .din1(mul_ln1118_fu_962_p1),
    .dout(mul_ln1118_fu_962_p2)
);

myproject_mul_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_11ns_26_1_1_U8(
    .din0(mul_ln1118_1_fu_969_p0),
    .din1(mul_ln1118_1_fu_969_p1),
    .dout(mul_ln1118_1_fu_969_p2)
);

myproject_mul_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_mul_16s_9ns_25_1_1_U9(
    .din0(data_buf_V_0_0_i_reg_1156),
    .din1(mul_ln1118_2_fu_976_p1),
    .dout(mul_ln1118_2_fu_976_p2)
);

myproject_mul_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_11s_26_1_1_U10(
    .din0(mul_ln1118_3_fu_983_p0),
    .din1(mul_ln1118_3_fu_983_p1),
    .dout(mul_ln1118_3_fu_983_p2)
);

myproject_mul_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_11s_26_1_1_U11(
    .din0(mul_ln1118_4_fu_990_p0),
    .din1(mul_ln1118_4_fu_990_p1),
    .dout(mul_ln1118_4_fu_990_p2)
);

myproject_mul_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_10ns_26_1_1_U12(
    .din0(mul_ln1118_5_fu_997_p0),
    .din1(mul_ln1118_5_fu_997_p1),
    .dout(mul_ln1118_5_fu_997_p2)
);

myproject_mul_mul_16s_6ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 22 ))
myproject_mul_mul_16s_6ns_22_1_1_U13(
    .din0(data_buf_V_0_0_i_reg_1156),
    .din1(mul_ln1118_6_fu_1003_p1),
    .dout(mul_ln1118_6_fu_1003_p2)
);

myproject_mul_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
myproject_mul_mul_16s_9ns_25_1_1_U14(
    .din0(mul_ln1118_7_fu_1010_p0),
    .din1(mul_ln1118_7_fu_1010_p1),
    .dout(mul_ln1118_7_fu_1010_p2)
);

myproject_mul_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_10s_26_1_1_U15(
    .din0(mul_ln1118_8_fu_1016_p0),
    .din1(mul_ln1118_8_fu_1016_p1),
    .dout(mul_ln1118_8_fu_1016_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_0_preg <= res_0_V_1_fu_514_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_10_preg <= res_10_V_1_fu_522_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_11_preg <= res_11_V_1_fu_562_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_12_preg <= res_12_V_1_fu_631_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_13_preg <= res_13_V_1_fu_608_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_14_preg <= res_14_V_1_fu_601_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_15_preg <= res_15_V_1_fu_593_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_16_preg <= res_16_V_1_fu_585_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_17_preg <= res_17_V_1_fu_577_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_18_preg <= res_18_V_1_fu_569_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_1_preg <= res_1_V_1_fu_554_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_2_preg <= res_2_V_1_fu_623_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_3_preg <= res_3_V_1_fu_646_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_4_preg <= res_4_V_1_fu_677_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_5_preg <= res_5_V_1_fu_725_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_6_preg <= res_6_V_1_fu_741_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_7_preg <= res_7_V_1_fu_709_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_8_preg <= res_8_V_1_fu_693_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_9_preg <= res_9_V_1_fu_662_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_52)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233 <= ap_phi_mux_data_V_load_rewind_phi_fu_207_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233 <= data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233 <= ap_phi_reg_pp0_iter0_data_V_load_phi_reg_233;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_1147 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        do_init_reg_186 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_186 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_1147 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        i_part_0_i_i79_reg_218 <= i_part_reg_1151;
    end else if ((((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        i_part_0_i_i79_reg_218 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_1147_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_05_i_idx_i78_reg_245 <= add_ln96_fu_489_p2;
    end else if ((((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_05_i_idx_i78_reg_245 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_0_1_V_reg_1182 <= {{mul_ln1118_1_fu_969_p2[25:10]}};
        acc_0_3_V_reg_1193 <= {{mul_ln1118_3_fu_983_p2[25:10]}};
        acc_0_4_V_reg_1199 <= {{mul_ln1118_4_fu_990_p2[25:10]}};
        sext_ln1118_1_reg_1165 <= sext_ln1118_1_fu_289_p1;
        sext_ln1118_2_reg_1170 <= sext_ln1118_2_fu_292_p1;
        trunc_ln708_2_reg_1188 <= {{mul_ln1118_2_fu_976_p2[24:10]}};
        trunc_ln_reg_1176 <= {{mul_ln1118_fu_962_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_load_phi_reg_233 <= ap_phi_reg_pp0_iter1_data_V_load_phi_reg_233;
        i_part_reg_1151 <= i_part_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_1147 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        data_V_load_rewind_reg_203 <= data_V_load_phi_reg_233;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        data_buf_V_0_0_06281_i77_fu_176 <= grp_fill_buffer_fu_259_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        data_buf_V_0_0_i_reg_1156 <= grp_fill_buffer_fu_259_ap_return;
        icmp_ln36_reg_1147 <= icmp_ln36_fu_268_p2;
        icmp_ln36_reg_1147_pp0_iter1_reg <= icmp_ln36_reg_1147;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_0_V_02168_fu_164 <= res_0_V_1_fu_514_p3;
        res_10_V_03128_fu_124 <= res_10_V_1_fu_522_p3;
        res_11_V_02934_fu_132 <= res_11_V_1_fu_562_p3;
        res_12_V_02840_fu_136 <= res_12_V_1_fu_631_p3;
        res_13_V_02646_fu_144 <= res_13_V_1_fu_608_p3;
        res_14_V_02552_fu_148 <= res_14_V_1_fu_601_p3;
        res_15_V_02358_fu_156 <= res_15_V_1_fu_593_p3;
        res_16_V_02264_fu_160 <= res_16_V_1_fu_585_p3;
        res_17_V_02070_fu_168 <= res_17_V_1_fu_577_p3;
        res_18_V_01976_fu_172 <= res_18_V_1_fu_569_p3;
        res_1_V_02456_fu_152 <= res_1_V_1_fu_554_p3;
        res_2_V_02744_fu_140 <= res_2_V_1_fu_623_p3;
        res_3_V_03032_fu_128 <= res_3_V_1_fu_646_p3;
        res_4_V_03320_fu_116 <= res_4_V_1_fu_677_p3;
        res_5_V_0368_fu_104 <= res_5_V_1_fu_725_p3;
        res_6_V_0374_fu_100 <= res_6_V_1_fu_741_p3;
        res_7_V_03510_fu_108 <= res_7_V_1_fu_709_p3;
        res_8_V_03416_fu_112 <= res_8_V_1_fu_693_p3;
        res_9_V_03222_fu_120 <= res_9_V_1_fu_662_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_reg_1147 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_data_V_load_rewind_phi_fu_207_p6 = data_V_load_phi_reg_233;
    end else begin
        ap_phi_mux_data_V_load_rewind_phi_fu_207_p6 = data_V_load_rewind_reg_203;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_174)) begin
        if ((icmp_ln36_reg_1147 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_191_p6 = 1'd1;
        end else if ((icmp_ln36_reg_1147 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_191_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_191_p6 = do_init_reg_186;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_191_p6 = do_init_reg_186;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_174)) begin
        if ((icmp_ln36_reg_1147 == 1'd1)) begin
            ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6 = 6'd0;
        end else if ((icmp_ln36_reg_1147 == 1'd0)) begin
            ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6 = i_part_reg_1151;
        end else begin
            ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6 = i_part_0_i_i79_reg_218;
        end
    end else begin
        ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6 = i_part_0_i_i79_reg_218;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_fu_268_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_0 = res_0_V_1_fu_514_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_1 = res_1_V_1_fu_554_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_10 = res_10_V_1_fu_522_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_11 = res_11_V_1_fu_562_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_12 = res_12_V_1_fu_631_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_13 = res_13_V_1_fu_608_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_14 = res_14_V_1_fu_601_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_15 = res_15_V_1_fu_593_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_16 = res_16_V_1_fu_585_p3;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_17 = res_17_V_1_fu_577_p3;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_18 = res_18_V_1_fu_569_p3;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_2 = res_2_V_1_fu_623_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_3 = res_3_V_1_fu_646_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_4 = res_4_V_1_fu_677_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_5 = res_5_V_1_fu_725_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_6 = res_6_V_1_fu_741_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_7 = res_7_V_1_fu_709_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_8 = res_8_V_1_fu_693_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln36_reg_1147_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_9 = res_9_V_1_fu_662_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        data_V_blk_n = data_V_empty_n;
    end else begin
        data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        data_V_read = 1'b1;
    end else begin
        data_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp43)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp41)))) begin
        grp_fill_buffer_fu_259_ap_ce = 1'b1;
    end else begin
        grp_fill_buffer_fu_259_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_2_V_fu_400_p1 = $signed(trunc_ln708_2_reg_1188);

assign acc_0_5_V_fu_403_p4 = {{mul_ln1118_5_fu_997_p2[25:10]}};

assign acc_0_6_V_fu_421_p1 = $signed(trunc_ln708_6_fu_412_p4);

assign acc_0_7_V_fu_434_p1 = $signed(trunc_ln708_7_fu_425_p4);

assign acc_0_8_V_fu_438_p4 = {{mul_ln1118_8_fu_1016_p2[25:10]}};

assign acc_0_9_V_fu_485_p1 = $signed(trunc_ln708_9_fu_475_p4);

assign add_ln1118_fu_469_p2 = ($signed(sext_ln1118_4_fu_465_p1) + $signed(sext_ln1118_3_fu_454_p1));

assign add_ln96_fu_489_p2 = (p_05_i_idx_i78_reg_245 + 10'd10);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp41 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((data_V_empty_n == 1'b0) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp43 = ((data_V_empty_n == 1'b0) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((data_V_empty_n == 1'b0) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0_ignore_call23 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((data_V_empty_n == 1'b0) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1));
end

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0_ignore_call23 = ((data_V_empty_n == 1'b0) & (ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1));
end

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2_ignore_call23 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter2_ignore_call23 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_174 = ((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_52 = ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_data_V_load_phi_reg_233 = 'bx;

assign i_part_fu_278_p2 = (i_part_0_i_i79_reg_218 + 6'd1);

assign icmp_ln203_1_fu_548_p2 = ((p_05_i_idx1_14_t_i_fu_529_p2 == 10'd11) ? 1'b1 : 1'b0);

assign icmp_ln203_2_fu_495_p2 = ((p_05_i_idx_i78_reg_245 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln203_3_fu_501_p2 = ((p_05_i_idx_i78_reg_245 == 10'd10) ? 1'b1 : 1'b0);

assign icmp_ln203_fu_535_p2 = ((p_05_i_idx1_14_t_i_fu_529_p2 == 10'd1) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_268_p2 = ((ap_phi_mux_i_part_0_i_i79_phi_fu_222_p6 == 6'd56) ? 1'b1 : 1'b0);

assign mul_ln1118_1_fu_969_p0 = sext_ln1118_2_fu_292_p1;

assign mul_ln1118_1_fu_969_p1 = 26'd688;

assign mul_ln1118_2_fu_976_p1 = 25'd210;

assign mul_ln1118_3_fu_983_p0 = sext_ln1118_2_fu_292_p1;

assign mul_ln1118_3_fu_983_p1 = 26'd67108110;

assign mul_ln1118_4_fu_990_p0 = sext_ln1118_2_fu_292_p1;

assign mul_ln1118_4_fu_990_p1 = 26'd67108280;

assign mul_ln1118_5_fu_997_p0 = sext_ln1118_2_reg_1170;

assign mul_ln1118_5_fu_997_p1 = 26'd296;

assign mul_ln1118_6_fu_1003_p1 = 22'd26;

assign mul_ln1118_7_fu_1010_p0 = sext_ln1118_1_reg_1165;

assign mul_ln1118_7_fu_1010_p1 = 25'd168;

assign mul_ln1118_8_fu_1016_p0 = sext_ln1118_2_reg_1170;

assign mul_ln1118_8_fu_1016_p1 = 26'd67108571;

assign mul_ln1118_fu_962_p0 = sext_ln1118_2_fu_292_p1;

assign mul_ln1118_fu_962_p1 = 26'd67108503;

assign p_05_i_idx1_14_t_i_fu_529_p2 = (p_05_i_idx_i78_reg_245 | 10'd1);

assign res_0_V_1_fu_514_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_0_V_02168_fu_164 : select_ln203_9_fu_507_p3);

assign res_10_V_1_fu_522_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? trunc_ln_reg_1176 : res_10_V_03128_fu_124);

assign res_11_V_1_fu_562_p3 = ((icmp_ln203_1_fu_548_p2[0:0] === 1'b1) ? acc_0_1_V_reg_1182 : res_11_V_02934_fu_132);

assign res_12_V_1_fu_631_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_2_V_fu_400_p1 : res_12_V_02840_fu_136);

assign res_13_V_1_fu_608_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_3_V_reg_1193 : res_13_V_02646_fu_144);

assign res_14_V_1_fu_601_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_4_V_reg_1199 : res_14_V_02552_fu_148);

assign res_15_V_1_fu_593_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_5_V_fu_403_p4 : res_15_V_02358_fu_156);

assign res_16_V_1_fu_585_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_6_V_fu_421_p1 : res_16_V_02264_fu_160);

assign res_17_V_1_fu_577_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_7_V_fu_434_p1 : res_17_V_02070_fu_168);

assign res_18_V_1_fu_569_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? acc_0_8_V_fu_438_p4 : res_18_V_01976_fu_172);

assign res_1_V_1_fu_554_p3 = ((icmp_ln203_1_fu_548_p2[0:0] === 1'b1) ? res_1_V_02456_fu_152 : select_ln203_fu_541_p3);

assign res_2_V_1_fu_623_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_2_V_02744_fu_140 : select_ln203_1_fu_615_p3);

assign res_3_V_1_fu_646_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_3_V_03032_fu_128 : select_ln203_2_fu_639_p3);

assign res_4_V_1_fu_677_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_4_V_03320_fu_116 : select_ln203_4_fu_670_p3);

assign res_5_V_1_fu_725_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_5_V_0368_fu_104 : select_ln203_7_fu_717_p3);

assign res_6_V_1_fu_741_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_6_V_0374_fu_100 : select_ln203_8_fu_733_p3);

assign res_7_V_1_fu_709_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_7_V_03510_fu_108 : select_ln203_6_fu_701_p3);

assign res_8_V_1_fu_693_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_8_V_03416_fu_112 : select_ln203_5_fu_685_p3);

assign res_9_V_1_fu_662_p3 = ((icmp_ln203_3_fu_501_p2[0:0] === 1'b1) ? res_9_V_03222_fu_120 : select_ln203_3_fu_654_p3);

assign select_ln203_1_fu_615_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_2_V_fu_400_p1 : res_2_V_02744_fu_140);

assign select_ln203_2_fu_639_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_3_V_reg_1193 : res_3_V_03032_fu_128);

assign select_ln203_3_fu_654_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_9_V_fu_485_p1 : res_9_V_03222_fu_120);

assign select_ln203_4_fu_670_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_4_V_reg_1199 : res_4_V_03320_fu_116);

assign select_ln203_5_fu_685_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_8_V_fu_438_p4 : res_8_V_03416_fu_112);

assign select_ln203_6_fu_701_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_7_V_fu_434_p1 : res_7_V_03510_fu_108);

assign select_ln203_7_fu_717_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_5_V_fu_403_p4 : res_5_V_0368_fu_104);

assign select_ln203_8_fu_733_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? acc_0_6_V_fu_421_p1 : res_6_V_0374_fu_100);

assign select_ln203_9_fu_507_p3 = ((icmp_ln203_2_fu_495_p2[0:0] === 1'b1) ? trunc_ln_reg_1176 : res_0_V_02168_fu_164);

assign select_ln203_fu_541_p3 = ((icmp_ln203_fu_535_p2[0:0] === 1'b1) ? acc_0_1_V_reg_1182 : res_1_V_02456_fu_152);

assign sext_ln1118_1_fu_289_p1 = data_buf_V_0_0_i_reg_1156;

assign sext_ln1118_2_fu_292_p1 = data_buf_V_0_0_i_reg_1156;

assign sext_ln1118_3_fu_454_p1 = $signed(shl_ln_fu_447_p3);

assign sext_ln1118_4_fu_465_p1 = $signed(shl_ln1118_1_fu_458_p3);

assign shl_ln1118_1_fu_458_p3 = {{data_buf_V_0_0_i_reg_1156}, {1'd0}};

assign shl_ln_fu_447_p3 = {{data_buf_V_0_0_i_reg_1156}, {8'd0}};

assign trunc_ln708_6_fu_412_p4 = {{mul_ln1118_6_fu_1003_p2[21:10]}};

assign trunc_ln708_7_fu_425_p4 = {{mul_ln1118_7_fu_1010_p2[24:10]}};

assign trunc_ln708_9_fu_475_p4 = {{add_ln1118_fu_469_p2[24:10]}};

endmodule //pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_s
