// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _myproject_HH_
#define _myproject_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_entry181.h"
#include "pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_s.h"
#include "pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_s.h"
#include "fifo_w912_d2_A.h"
#include "start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0.h"
#include "start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0.h"

namespace ap_rtl {

struct myproject : public sc_module {
    // Port declarations 9
    sc_in< sc_lv<912> > input_1_V;
    sc_in< sc_lv<16> > layer6_out_0_V;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > input_1_V_ap_vld;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    myproject(sc_module_name name);
    SC_HAS_PROCESS(myproject);

    ~myproject();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    myproject_entry181* myproject_entry181_U0;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_s* pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_s* pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0;
    fifo_w912_d2_A* input_1_V_c_U;
    fifo_w912_d2_A* input_1_V_c1_U;
    start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0* start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_U;
    start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0* start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_U;
    sc_signal< sc_logic > myproject_entry181_U0_ap_start;
    sc_signal< sc_logic > myproject_entry181_U0_start_full_n;
    sc_signal< sc_logic > myproject_entry181_U0_ap_done;
    sc_signal< sc_logic > myproject_entry181_U0_ap_continue;
    sc_signal< sc_logic > myproject_entry181_U0_ap_idle;
    sc_signal< sc_logic > myproject_entry181_U0_ap_ready;
    sc_signal< sc_logic > myproject_entry181_U0_start_out;
    sc_signal< sc_logic > myproject_entry181_U0_start_write;
    sc_signal< sc_lv<912> > myproject_entry181_U0_input_1_V_out_din;
    sc_signal< sc_logic > myproject_entry181_U0_input_1_V_out_write;
    sc_signal< sc_lv<912> > myproject_entry181_U0_input_1_V_out1_din;
    sc_signal< sc_logic > myproject_entry181_U0_input_1_V_out1_write;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_start;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_done;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_continue;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_idle;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_ready;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_data_V_read;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_start;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_done;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_continue;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_idle;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_ready;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_data_V_read;
    sc_signal< sc_logic > input_1_V_c_full_n;
    sc_signal< sc_lv<912> > input_1_V_c_dout;
    sc_signal< sc_logic > input_1_V_c_empty_n;
    sc_signal< sc_logic > input_1_V_c1_full_n;
    sc_signal< sc_lv<912> > input_1_V_c1_dout;
    sc_signal< sc_logic > input_1_V_c1_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_lv<1> > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_din;
    sc_signal< sc_logic > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_full_n;
    sc_signal< sc_lv<1> > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_dout;
    sc_signal< sc_logic > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_din;
    sc_signal< sc_logic > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_full_n;
    sc_signal< sc_lv<1> > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_dout;
    sc_signal< sc_logic > start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_empty_n;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_start_full_n;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_start_write;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_start_full_n;
    sc_signal< sc_logic > pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_start_write;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_myproject_entry181_U0_ap_continue();
    void thread_myproject_entry181_U0_ap_start();
    void thread_myproject_entry181_U0_start_full_n();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_continue();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_ap_start();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_start_full_n();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_start_write();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_continue();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_ap_start();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_start_full_n();
    void thread_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_start_write();
    void thread_start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config10_U0_din();
    void thread_start_for_pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config9_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
