// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module klloss_ap_fixed_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        mean_0_V_read,
        mean_1_V_read,
        mean_2_V_read,
        mean_3_V_read,
        mean_4_V_read,
        mean_5_V_read,
        mean_6_V_read,
        mean_7_V_read,
        mean_8_V_read,
        mean_9_V_read,
        mean_10_V_read,
        mean_11_V_read,
        mean_12_V_read,
        mean_13_V_read,
        mean_14_V_read,
        mean_15_V_read,
        mean_16_V_read,
        mean_17_V_read,
        mean_18_V_read,
        log_var_0_V_read,
        log_var_1_V_read,
        log_var_2_V_read,
        log_var_3_V_read,
        log_var_4_V_read,
        log_var_5_V_read,
        log_var_6_V_read,
        log_var_7_V_read,
        log_var_8_V_read,
        log_var_9_V_read,
        log_var_10_V_read,
        log_var_11_V_read,
        log_var_12_V_read,
        log_var_13_V_read,
        log_var_14_V_read,
        log_var_15_V_read,
        log_var_16_V_read,
        log_var_17_V_read,
        log_var_18_V_read,
        res_V,
        res_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] mean_0_V_read;
input  [15:0] mean_1_V_read;
input  [15:0] mean_2_V_read;
input  [15:0] mean_3_V_read;
input  [15:0] mean_4_V_read;
input  [15:0] mean_5_V_read;
input  [15:0] mean_6_V_read;
input  [15:0] mean_7_V_read;
input  [15:0] mean_8_V_read;
input  [15:0] mean_9_V_read;
input  [15:0] mean_10_V_read;
input  [15:0] mean_11_V_read;
input  [15:0] mean_12_V_read;
input  [15:0] mean_13_V_read;
input  [15:0] mean_14_V_read;
input  [15:0] mean_15_V_read;
input  [15:0] mean_16_V_read;
input  [15:0] mean_17_V_read;
input  [15:0] mean_18_V_read;
input  [15:0] log_var_0_V_read;
input  [15:0] log_var_1_V_read;
input  [15:0] log_var_2_V_read;
input  [15:0] log_var_3_V_read;
input  [15:0] log_var_4_V_read;
input  [15:0] log_var_5_V_read;
input  [15:0] log_var_6_V_read;
input  [15:0] log_var_7_V_read;
input  [15:0] log_var_8_V_read;
input  [15:0] log_var_9_V_read;
input  [15:0] log_var_10_V_read;
input  [15:0] log_var_11_V_read;
input  [15:0] log_var_12_V_read;
input  [15:0] log_var_13_V_read;
input  [15:0] log_var_14_V_read;
input  [15:0] log_var_15_V_read;
input  [15:0] log_var_16_V_read;
input  [15:0] log_var_17_V_read;
input  [15:0] log_var_18_V_read;
output  [15:0] res_V;
output   res_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] exp_table1_address0;
reg    exp_table1_ce0;
wire   [16:0] exp_table1_q0;
wire   [9:0] exp_table1_address1;
reg    exp_table1_ce1;
wire   [16:0] exp_table1_q1;
wire   [9:0] exp_table1_address2;
reg    exp_table1_ce2;
wire   [16:0] exp_table1_q2;
wire   [9:0] exp_table1_address3;
reg    exp_table1_ce3;
wire   [16:0] exp_table1_q3;
wire   [9:0] exp_table1_address4;
reg    exp_table1_ce4;
wire   [16:0] exp_table1_q4;
wire   [9:0] exp_table1_address5;
reg    exp_table1_ce5;
wire   [16:0] exp_table1_q5;
wire   [9:0] exp_table1_address6;
reg    exp_table1_ce6;
wire   [16:0] exp_table1_q6;
wire   [9:0] exp_table1_address7;
reg    exp_table1_ce7;
wire   [16:0] exp_table1_q7;
wire   [9:0] exp_table1_address8;
reg    exp_table1_ce8;
wire   [16:0] exp_table1_q8;
wire   [9:0] exp_table1_address9;
reg    exp_table1_ce9;
wire   [16:0] exp_table1_q9;
wire   [9:0] exp_table1_address10;
reg    exp_table1_ce10;
wire   [16:0] exp_table1_q10;
wire   [9:0] exp_table1_address11;
reg    exp_table1_ce11;
wire   [16:0] exp_table1_q11;
wire   [9:0] exp_table1_address12;
reg    exp_table1_ce12;
wire   [16:0] exp_table1_q12;
wire   [9:0] exp_table1_address13;
reg    exp_table1_ce13;
wire   [16:0] exp_table1_q13;
wire   [9:0] exp_table1_address14;
reg    exp_table1_ce14;
wire   [16:0] exp_table1_q14;
wire   [9:0] exp_table1_address15;
reg    exp_table1_ce15;
wire   [16:0] exp_table1_q15;
wire   [9:0] exp_table1_address16;
reg    exp_table1_ce16;
wire   [16:0] exp_table1_q16;
wire   [9:0] exp_table1_address17;
reg    exp_table1_ce17;
wire   [16:0] exp_table1_q17;
wire   [9:0] exp_table1_address18;
reg    exp_table1_ce18;
wire   [16:0] exp_table1_q18;
reg   [15:0] log_var_18_V_read_1_reg_2829;
reg   [15:0] log_var_17_V_read_1_reg_2834;
reg   [15:0] log_var_16_V_read_1_reg_2839;
reg   [15:0] log_var_15_V_read_1_reg_2844;
reg   [15:0] log_var_14_V_read_1_reg_2849;
reg   [15:0] log_var_13_V_read_1_reg_2854;
reg   [15:0] log_var_12_V_read_1_reg_2859;
reg   [15:0] log_var_11_V_read_1_reg_2864;
reg   [15:0] log_var_10_V_read_1_reg_2869;
reg   [15:0] log_var_9_V_read_1_reg_2874;
reg   [15:0] log_var_8_V_read_1_reg_2879;
reg   [15:0] log_var_7_V_read_1_reg_2884;
reg   [15:0] log_var_6_V_read_1_reg_2889;
reg   [15:0] log_var_5_V_read_1_reg_2894;
reg   [15:0] log_var_4_V_read_1_reg_2899;
reg   [15:0] log_var_3_V_read_1_reg_2904;
reg   [15:0] log_var_2_V_read_1_reg_2909;
reg   [15:0] log_var_1_V_read_1_reg_2914;
reg   [15:0] log_var_0_V_read_1_reg_2919;
reg   [15:0] trunc_ln_reg_2924;
reg   [15:0] trunc_ln708_1_reg_2929;
reg   [15:0] trunc_ln708_s_reg_2934;
reg   [15:0] trunc_ln708_3_reg_2939;
reg   [15:0] trunc_ln708_4_reg_2944;
reg   [15:0] trunc_ln708_5_reg_2949;
reg   [15:0] trunc_ln708_6_reg_2954;
reg   [15:0] trunc_ln708_7_reg_2959;
reg   [15:0] trunc_ln708_8_reg_2964;
reg   [15:0] trunc_ln708_9_reg_2969;
reg   [15:0] trunc_ln708_10_reg_2974;
reg   [15:0] trunc_ln708_11_reg_2979;
reg   [15:0] trunc_ln708_12_reg_2984;
reg   [15:0] trunc_ln708_13_reg_2989;
reg   [15:0] trunc_ln708_14_reg_2994;
reg   [15:0] trunc_ln708_15_reg_2999;
reg   [15:0] trunc_ln708_16_reg_3004;
reg   [15:0] trunc_ln708_17_reg_3009;
reg   [15:0] trunc_ln708_18_reg_3014;
wire   [15:0] add_ln703_21_fu_2550_p2;
reg   [15:0] add_ln703_21_reg_3114;
wire   [15:0] add_ln703_25_fu_2574_p2;
reg   [15:0] add_ln703_25_reg_3119;
wire   [15:0] add_ln703_35_fu_2628_p2;
reg   [15:0] add_ln703_35_reg_3124;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln559_fu_911_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln559_1_fu_980_p1;
wire   [63:0] zext_ln559_2_fu_1049_p1;
wire   [63:0] zext_ln559_3_fu_1118_p1;
wire   [63:0] zext_ln559_4_fu_1187_p1;
wire   [63:0] zext_ln559_5_fu_1256_p1;
wire   [63:0] zext_ln559_6_fu_1325_p1;
wire   [63:0] zext_ln559_7_fu_1394_p1;
wire   [63:0] zext_ln559_8_fu_1463_p1;
wire   [63:0] zext_ln559_9_fu_1532_p1;
wire   [63:0] zext_ln559_10_fu_1601_p1;
wire   [63:0] zext_ln559_11_fu_1670_p1;
wire   [63:0] zext_ln559_12_fu_1739_p1;
wire   [63:0] zext_ln559_13_fu_1808_p1;
wire   [63:0] zext_ln559_14_fu_1877_p1;
wire   [63:0] zext_ln559_15_fu_1946_p1;
wire   [63:0] zext_ln559_16_fu_2015_p1;
wire   [63:0] zext_ln559_17_fu_2084_p1;
wire   [63:0] zext_ln559_18_fu_2153_p1;
reg    ap_block_pp0_stage0_01001;
wire  signed [25:0] mul_ln1118_fu_2689_p2;
wire  signed [25:0] mul_ln1118_18_fu_2696_p2;
wire  signed [25:0] mul_ln1118_19_fu_2703_p2;
wire  signed [25:0] mul_ln1118_20_fu_2710_p2;
wire  signed [25:0] mul_ln1118_21_fu_2717_p2;
wire  signed [25:0] mul_ln1118_22_fu_2724_p2;
wire  signed [25:0] mul_ln1118_23_fu_2731_p2;
wire  signed [25:0] mul_ln1118_24_fu_2738_p2;
wire  signed [25:0] mul_ln1118_25_fu_2745_p2;
wire  signed [25:0] mul_ln1118_26_fu_2752_p2;
wire  signed [25:0] mul_ln1118_27_fu_2759_p2;
wire  signed [25:0] mul_ln1118_28_fu_2766_p2;
wire  signed [25:0] mul_ln1118_29_fu_2773_p2;
wire  signed [25:0] mul_ln1118_30_fu_2780_p2;
wire  signed [25:0] mul_ln1118_31_fu_2787_p2;
wire  signed [25:0] mul_ln1118_32_fu_2794_p2;
wire  signed [25:0] mul_ln1118_33_fu_2801_p2;
wire  signed [25:0] mul_ln1118_34_fu_2808_p2;
wire  signed [25:0] mul_ln1118_35_fu_2815_p2;
wire  signed [21:0] shl_ln_fu_847_p3;
wire  signed [22:0] sext_ln1118_25_fu_855_p1;
wire   [22:0] add_ln1192_fu_859_p2;
wire   [0:0] tmp_19_fu_871_p3;
wire   [21:0] add_ln1495_fu_865_p2;
wire   [21:0] select_ln68_fu_879_p3;
wire   [0:0] icmp_ln1494_fu_887_p2;
wire   [11:0] tmp_fu_893_p4;
wire   [11:0] select_ln70_fu_903_p3;
wire  signed [21:0] shl_ln1118_2_fu_916_p3;
wire  signed [22:0] sext_ln1118_26_fu_924_p1;
wire   [22:0] add_ln1192_1_fu_928_p2;
wire   [0:0] tmp_20_fu_940_p3;
wire   [21:0] add_ln1495_1_fu_934_p2;
wire   [21:0] select_ln68_1_fu_948_p3;
wire   [0:0] icmp_ln1494_1_fu_956_p2;
wire   [11:0] tmp_1_fu_962_p4;
wire   [11:0] select_ln70_1_fu_972_p3;
wire  signed [21:0] shl_ln1118_3_fu_985_p3;
wire  signed [22:0] sext_ln1118_27_fu_993_p1;
wire   [22:0] add_ln1192_2_fu_997_p2;
wire   [0:0] tmp_21_fu_1009_p3;
wire   [21:0] add_ln1495_2_fu_1003_p2;
wire   [21:0] select_ln68_2_fu_1017_p3;
wire   [0:0] icmp_ln1494_2_fu_1025_p2;
wire   [11:0] tmp_2_fu_1031_p4;
wire   [11:0] select_ln70_2_fu_1041_p3;
wire  signed [21:0] shl_ln1118_4_fu_1054_p3;
wire  signed [22:0] sext_ln1118_28_fu_1062_p1;
wire   [22:0] add_ln1192_3_fu_1066_p2;
wire   [0:0] tmp_22_fu_1078_p3;
wire   [21:0] add_ln1495_3_fu_1072_p2;
wire   [21:0] select_ln68_3_fu_1086_p3;
wire   [0:0] icmp_ln1494_3_fu_1094_p2;
wire   [11:0] tmp_3_fu_1100_p4;
wire   [11:0] select_ln70_3_fu_1110_p3;
wire  signed [21:0] shl_ln1118_5_fu_1123_p3;
wire  signed [22:0] sext_ln1118_29_fu_1131_p1;
wire   [22:0] add_ln1192_4_fu_1135_p2;
wire   [0:0] tmp_23_fu_1147_p3;
wire   [21:0] add_ln1495_4_fu_1141_p2;
wire   [21:0] select_ln68_4_fu_1155_p3;
wire   [0:0] icmp_ln1494_4_fu_1163_p2;
wire   [11:0] tmp_4_fu_1169_p4;
wire   [11:0] select_ln70_4_fu_1179_p3;
wire  signed [21:0] shl_ln1118_6_fu_1192_p3;
wire  signed [22:0] sext_ln1118_30_fu_1200_p1;
wire   [22:0] add_ln1192_5_fu_1204_p2;
wire   [0:0] tmp_24_fu_1216_p3;
wire   [21:0] add_ln1495_5_fu_1210_p2;
wire   [21:0] select_ln68_5_fu_1224_p3;
wire   [0:0] icmp_ln1494_5_fu_1232_p2;
wire   [11:0] tmp_5_fu_1238_p4;
wire   [11:0] select_ln70_5_fu_1248_p3;
wire  signed [21:0] shl_ln1118_7_fu_1261_p3;
wire  signed [22:0] sext_ln1118_31_fu_1269_p1;
wire   [22:0] add_ln1192_6_fu_1273_p2;
wire   [0:0] tmp_25_fu_1285_p3;
wire   [21:0] add_ln1495_6_fu_1279_p2;
wire   [21:0] select_ln68_6_fu_1293_p3;
wire   [0:0] icmp_ln1494_6_fu_1301_p2;
wire   [11:0] tmp_6_fu_1307_p4;
wire   [11:0] select_ln70_6_fu_1317_p3;
wire  signed [21:0] shl_ln1118_8_fu_1330_p3;
wire  signed [22:0] sext_ln1118_32_fu_1338_p1;
wire   [22:0] add_ln1192_7_fu_1342_p2;
wire   [0:0] tmp_26_fu_1354_p3;
wire   [21:0] add_ln1495_7_fu_1348_p2;
wire   [21:0] select_ln68_7_fu_1362_p3;
wire   [0:0] icmp_ln1494_7_fu_1370_p2;
wire   [11:0] tmp_7_fu_1376_p4;
wire   [11:0] select_ln70_7_fu_1386_p3;
wire  signed [21:0] shl_ln1118_9_fu_1399_p3;
wire  signed [22:0] sext_ln1118_33_fu_1407_p1;
wire   [22:0] add_ln1192_8_fu_1411_p2;
wire   [0:0] tmp_27_fu_1423_p3;
wire   [21:0] add_ln1495_8_fu_1417_p2;
wire   [21:0] select_ln68_8_fu_1431_p3;
wire   [0:0] icmp_ln1494_8_fu_1439_p2;
wire   [11:0] tmp_8_fu_1445_p4;
wire   [11:0] select_ln70_8_fu_1455_p3;
wire  signed [21:0] shl_ln1118_s_fu_1468_p3;
wire  signed [22:0] sext_ln1118_34_fu_1476_p1;
wire   [22:0] add_ln1192_9_fu_1480_p2;
wire   [0:0] tmp_28_fu_1492_p3;
wire   [21:0] add_ln1495_9_fu_1486_p2;
wire   [21:0] select_ln68_9_fu_1500_p3;
wire   [0:0] icmp_ln1494_9_fu_1508_p2;
wire   [11:0] tmp_9_fu_1514_p4;
wire   [11:0] select_ln70_9_fu_1524_p3;
wire  signed [21:0] shl_ln1118_1_fu_1537_p3;
wire  signed [22:0] sext_ln1118_35_fu_1545_p1;
wire   [22:0] add_ln1192_10_fu_1549_p2;
wire   [0:0] tmp_29_fu_1561_p3;
wire   [21:0] add_ln1495_10_fu_1555_p2;
wire   [21:0] select_ln68_10_fu_1569_p3;
wire   [0:0] icmp_ln1494_10_fu_1577_p2;
wire   [11:0] tmp_s_fu_1583_p4;
wire   [11:0] select_ln70_10_fu_1593_p3;
wire  signed [21:0] shl_ln1118_10_fu_1606_p3;
wire  signed [22:0] sext_ln1118_36_fu_1614_p1;
wire   [22:0] add_ln1192_11_fu_1618_p2;
wire   [0:0] tmp_30_fu_1630_p3;
wire   [21:0] add_ln1495_11_fu_1624_p2;
wire   [21:0] select_ln68_11_fu_1638_p3;
wire   [0:0] icmp_ln1494_11_fu_1646_p2;
wire   [11:0] tmp_10_fu_1652_p4;
wire   [11:0] select_ln70_11_fu_1662_p3;
wire  signed [21:0] shl_ln1118_11_fu_1675_p3;
wire  signed [22:0] sext_ln1118_37_fu_1683_p1;
wire   [22:0] add_ln1192_12_fu_1687_p2;
wire   [0:0] tmp_31_fu_1699_p3;
wire   [21:0] add_ln1495_12_fu_1693_p2;
wire   [21:0] select_ln68_12_fu_1707_p3;
wire   [0:0] icmp_ln1494_12_fu_1715_p2;
wire   [11:0] tmp_11_fu_1721_p4;
wire   [11:0] select_ln70_12_fu_1731_p3;
wire  signed [21:0] shl_ln1118_12_fu_1744_p3;
wire  signed [22:0] sext_ln1118_38_fu_1752_p1;
wire   [22:0] add_ln1192_13_fu_1756_p2;
wire   [0:0] tmp_32_fu_1768_p3;
wire   [21:0] add_ln1495_13_fu_1762_p2;
wire   [21:0] select_ln68_13_fu_1776_p3;
wire   [0:0] icmp_ln1494_13_fu_1784_p2;
wire   [11:0] tmp_12_fu_1790_p4;
wire   [11:0] select_ln70_13_fu_1800_p3;
wire  signed [21:0] shl_ln1118_13_fu_1813_p3;
wire  signed [22:0] sext_ln1118_39_fu_1821_p1;
wire   [22:0] add_ln1192_14_fu_1825_p2;
wire   [0:0] tmp_33_fu_1837_p3;
wire   [21:0] add_ln1495_14_fu_1831_p2;
wire   [21:0] select_ln68_14_fu_1845_p3;
wire   [0:0] icmp_ln1494_14_fu_1853_p2;
wire   [11:0] tmp_13_fu_1859_p4;
wire   [11:0] select_ln70_14_fu_1869_p3;
wire  signed [21:0] shl_ln1118_14_fu_1882_p3;
wire  signed [22:0] sext_ln1118_40_fu_1890_p1;
wire   [22:0] add_ln1192_15_fu_1894_p2;
wire   [0:0] tmp_34_fu_1906_p3;
wire   [21:0] add_ln1495_15_fu_1900_p2;
wire   [21:0] select_ln68_15_fu_1914_p3;
wire   [0:0] icmp_ln1494_15_fu_1922_p2;
wire   [11:0] tmp_14_fu_1928_p4;
wire   [11:0] select_ln70_15_fu_1938_p3;
wire  signed [21:0] shl_ln1118_15_fu_1951_p3;
wire  signed [22:0] sext_ln1118_41_fu_1959_p1;
wire   [22:0] add_ln1192_16_fu_1963_p2;
wire   [0:0] tmp_35_fu_1975_p3;
wire   [21:0] add_ln1495_16_fu_1969_p2;
wire   [21:0] select_ln68_16_fu_1983_p3;
wire   [0:0] icmp_ln1494_16_fu_1991_p2;
wire   [11:0] tmp_15_fu_1997_p4;
wire   [11:0] select_ln70_16_fu_2007_p3;
wire  signed [21:0] shl_ln1118_16_fu_2020_p3;
wire  signed [22:0] sext_ln1118_42_fu_2028_p1;
wire   [22:0] add_ln1192_17_fu_2032_p2;
wire   [0:0] tmp_36_fu_2044_p3;
wire   [21:0] add_ln1495_17_fu_2038_p2;
wire   [21:0] select_ln68_17_fu_2052_p3;
wire   [0:0] icmp_ln1494_17_fu_2060_p2;
wire   [11:0] tmp_16_fu_2066_p4;
wire   [11:0] select_ln70_17_fu_2076_p3;
wire  signed [21:0] shl_ln1118_17_fu_2089_p3;
wire  signed [22:0] sext_ln1118_43_fu_2097_p1;
wire   [22:0] add_ln1192_18_fu_2101_p2;
wire   [0:0] tmp_37_fu_2113_p3;
wire   [21:0] add_ln1495_18_fu_2107_p2;
wire   [21:0] select_ln68_18_fu_2121_p3;
wire   [0:0] icmp_ln1494_18_fu_2129_p2;
wire   [11:0] tmp_17_fu_2135_p4;
wire   [11:0] select_ln70_18_fu_2145_p3;
wire   [15:0] add_ln703_fu_2158_p2;
wire   [15:0] trunc_ln1193_fu_2253_p1;
wire   [15:0] add_ln703_1_fu_2163_p2;
wire   [15:0] trunc_ln1193_1_fu_2263_p1;
wire   [15:0] add_ln703_2_fu_2168_p2;
wire   [15:0] trunc_ln1193_2_fu_2273_p1;
wire   [15:0] add_ln703_3_fu_2173_p2;
wire   [15:0] trunc_ln1193_3_fu_2283_p1;
wire   [15:0] add_ln703_4_fu_2178_p2;
wire   [15:0] trunc_ln1193_4_fu_2293_p1;
wire   [15:0] add_ln703_5_fu_2183_p2;
wire   [15:0] trunc_ln1193_5_fu_2303_p1;
wire   [15:0] add_ln703_6_fu_2188_p2;
wire   [15:0] trunc_ln1193_6_fu_2313_p1;
wire   [15:0] add_ln703_7_fu_2193_p2;
wire   [15:0] trunc_ln1193_7_fu_2323_p1;
wire   [15:0] add_ln703_8_fu_2198_p2;
wire   [15:0] trunc_ln1193_8_fu_2333_p1;
wire   [15:0] add_ln703_9_fu_2203_p2;
wire   [15:0] trunc_ln1193_9_fu_2343_p1;
wire   [15:0] add_ln703_10_fu_2208_p2;
wire   [15:0] trunc_ln1193_10_fu_2353_p1;
wire   [15:0] add_ln703_11_fu_2213_p2;
wire   [15:0] trunc_ln1193_11_fu_2363_p1;
wire   [15:0] add_ln703_12_fu_2218_p2;
wire   [15:0] trunc_ln1193_12_fu_2373_p1;
wire   [15:0] add_ln703_13_fu_2223_p2;
wire   [15:0] trunc_ln1193_13_fu_2383_p1;
wire   [15:0] add_ln703_14_fu_2228_p2;
wire   [15:0] trunc_ln1193_14_fu_2393_p1;
wire   [15:0] add_ln703_15_fu_2233_p2;
wire   [15:0] trunc_ln1193_15_fu_2403_p1;
wire   [15:0] add_ln703_16_fu_2238_p2;
wire   [15:0] trunc_ln1193_16_fu_2413_p1;
wire   [15:0] add_ln703_17_fu_2243_p2;
wire   [15:0] trunc_ln1193_17_fu_2423_p1;
wire   [15:0] add_ln703_18_fu_2248_p2;
wire   [15:0] trunc_ln1193_18_fu_2433_p1;
wire   [15:0] sub_ln703_fu_2257_p2;
wire   [15:0] sub_ln703_1_fu_2267_p2;
wire   [15:0] sub_ln703_2_fu_2277_p2;
wire   [15:0] sub_ln703_3_fu_2287_p2;
wire   [15:0] sub_ln703_4_fu_2297_p2;
wire   [15:0] sub_ln703_5_fu_2307_p2;
wire   [15:0] sub_ln703_6_fu_2317_p2;
wire   [15:0] sub_ln703_7_fu_2327_p2;
wire   [15:0] sub_ln703_8_fu_2337_p2;
wire   [15:0] sub_ln703_9_fu_2347_p2;
wire   [15:0] sub_ln703_10_fu_2357_p2;
wire   [15:0] sub_ln703_11_fu_2367_p2;
wire   [15:0] sub_ln703_12_fu_2377_p2;
wire   [15:0] sub_ln703_13_fu_2387_p2;
wire   [15:0] sub_ln703_14_fu_2397_p2;
wire   [15:0] sub_ln703_15_fu_2407_p2;
wire   [15:0] sub_ln703_16_fu_2417_p2;
wire   [15:0] sub_ln703_17_fu_2427_p2;
wire   [15:0] sub_ln703_18_fu_2437_p2;
wire   [15:0] kl_17_V_fu_2528_p2;
wire   [15:0] kl_16_V_fu_2523_p2;
wire   [15:0] kl_18_V_fu_2533_p2;
wire   [15:0] kl_0_V_fu_2443_p2;
wire   [15:0] add_ln703_20_fu_2544_p2;
wire   [15:0] add_ln703_19_fu_2538_p2;
wire   [15:0] kl_1_V_fu_2448_p2;
wire   [15:0] kl_2_V_fu_2453_p2;
wire   [15:0] kl_4_V_fu_2463_p2;
wire   [15:0] kl_5_V_fu_2468_p2;
wire   [15:0] add_ln703_23_fu_2562_p2;
wire   [15:0] kl_3_V_fu_2458_p2;
wire   [15:0] add_ln703_24_fu_2568_p2;
wire   [15:0] add_ln703_22_fu_2556_p2;
wire   [15:0] kl_6_V_fu_2473_p2;
wire   [15:0] kl_7_V_fu_2478_p2;
wire   [15:0] kl_9_V_fu_2488_p2;
wire   [15:0] kl_10_V_fu_2493_p2;
wire   [15:0] add_ln703_28_fu_2586_p2;
wire   [15:0] kl_8_V_fu_2483_p2;
wire   [15:0] add_ln703_29_fu_2592_p2;
wire   [15:0] add_ln703_27_fu_2580_p2;
wire   [15:0] kl_11_V_fu_2498_p2;
wire   [15:0] kl_12_V_fu_2503_p2;
wire   [15:0] kl_14_V_fu_2513_p2;
wire   [15:0] kl_15_V_fu_2518_p2;
wire   [15:0] add_ln703_32_fu_2610_p2;
wire   [15:0] kl_13_V_fu_2508_p2;
wire   [15:0] add_ln703_33_fu_2616_p2;
wire   [15:0] add_ln703_31_fu_2604_p2;
wire   [15:0] add_ln703_34_fu_2622_p2;
wire   [15:0] add_ln703_30_fu_2598_p2;
wire   [15:0] add_ln703_26_fu_2634_p2;
wire  signed [15:0] kl_sum_V_fu_2638_p2;
wire  signed [22:0] r_V_fu_2822_p2;
wire   [12:0] trunc_ln708_19_fu_2647_p4;
wire   [21:0] tmp_18_fu_2656_p3;
wire  signed [22:0] sext_ln1118_44_fu_2664_p1;
wire   [22:0] r_V_1_fu_2668_p2;
wire   [12:0] tmp_38_fu_2674_p4;
wire  signed [15:0] mul_ln1118_fu_2689_p0;
wire  signed [25:0] sext_ln1118_fu_600_p1;
wire  signed [15:0] mul_ln1118_fu_2689_p1;
wire  signed [15:0] mul_ln1118_18_fu_2696_p0;
wire  signed [25:0] sext_ln1118_7_fu_613_p1;
wire  signed [15:0] mul_ln1118_18_fu_2696_p1;
wire  signed [15:0] mul_ln1118_19_fu_2703_p0;
wire  signed [25:0] sext_ln1118_8_fu_626_p1;
wire  signed [15:0] mul_ln1118_19_fu_2703_p1;
wire  signed [15:0] mul_ln1118_20_fu_2710_p0;
wire  signed [25:0] sext_ln1118_9_fu_639_p1;
wire  signed [15:0] mul_ln1118_20_fu_2710_p1;
wire  signed [15:0] mul_ln1118_21_fu_2717_p0;
wire  signed [25:0] sext_ln1118_10_fu_652_p1;
wire  signed [15:0] mul_ln1118_21_fu_2717_p1;
wire  signed [15:0] mul_ln1118_22_fu_2724_p0;
wire  signed [25:0] sext_ln1118_11_fu_665_p1;
wire  signed [15:0] mul_ln1118_22_fu_2724_p1;
wire  signed [15:0] mul_ln1118_23_fu_2731_p0;
wire  signed [25:0] sext_ln1118_12_fu_678_p1;
wire  signed [15:0] mul_ln1118_23_fu_2731_p1;
wire  signed [15:0] mul_ln1118_24_fu_2738_p0;
wire  signed [25:0] sext_ln1118_13_fu_691_p1;
wire  signed [15:0] mul_ln1118_24_fu_2738_p1;
wire  signed [15:0] mul_ln1118_25_fu_2745_p0;
wire  signed [25:0] sext_ln1118_14_fu_704_p1;
wire  signed [15:0] mul_ln1118_25_fu_2745_p1;
wire  signed [15:0] mul_ln1118_26_fu_2752_p0;
wire  signed [25:0] sext_ln1118_15_fu_717_p1;
wire  signed [15:0] mul_ln1118_26_fu_2752_p1;
wire  signed [15:0] mul_ln1118_27_fu_2759_p0;
wire  signed [25:0] sext_ln1118_16_fu_730_p1;
wire  signed [15:0] mul_ln1118_27_fu_2759_p1;
wire  signed [15:0] mul_ln1118_28_fu_2766_p0;
wire  signed [25:0] sext_ln1118_17_fu_743_p1;
wire  signed [15:0] mul_ln1118_28_fu_2766_p1;
wire  signed [15:0] mul_ln1118_29_fu_2773_p0;
wire  signed [25:0] sext_ln1118_18_fu_756_p1;
wire  signed [15:0] mul_ln1118_29_fu_2773_p1;
wire  signed [15:0] mul_ln1118_30_fu_2780_p0;
wire  signed [25:0] sext_ln1118_19_fu_769_p1;
wire  signed [15:0] mul_ln1118_30_fu_2780_p1;
wire  signed [15:0] mul_ln1118_31_fu_2787_p0;
wire  signed [25:0] sext_ln1118_20_fu_782_p1;
wire  signed [15:0] mul_ln1118_31_fu_2787_p1;
wire  signed [15:0] mul_ln1118_32_fu_2794_p0;
wire  signed [25:0] sext_ln1118_21_fu_795_p1;
wire  signed [15:0] mul_ln1118_32_fu_2794_p1;
wire  signed [15:0] mul_ln1118_33_fu_2801_p0;
wire  signed [25:0] sext_ln1118_22_fu_808_p1;
wire  signed [15:0] mul_ln1118_33_fu_2801_p1;
wire  signed [15:0] mul_ln1118_34_fu_2808_p0;
wire  signed [25:0] sext_ln1118_23_fu_821_p1;
wire  signed [15:0] mul_ln1118_34_fu_2808_p1;
wire  signed [15:0] mul_ln1118_35_fu_2815_p0;
wire  signed [25:0] sext_ln1118_24_fu_834_p1;
wire  signed [15:0] mul_ln1118_35_fu_2815_p1;
wire   [6:0] r_V_fu_2822_p0;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

klloss_ap_fixed_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_exp_table1 #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table1_address0),
    .ce0(exp_table1_ce0),
    .q0(exp_table1_q0),
    .address1(exp_table1_address1),
    .ce1(exp_table1_ce1),
    .q1(exp_table1_q1),
    .address2(exp_table1_address2),
    .ce2(exp_table1_ce2),
    .q2(exp_table1_q2),
    .address3(exp_table1_address3),
    .ce3(exp_table1_ce3),
    .q3(exp_table1_q3),
    .address4(exp_table1_address4),
    .ce4(exp_table1_ce4),
    .q4(exp_table1_q4),
    .address5(exp_table1_address5),
    .ce5(exp_table1_ce5),
    .q5(exp_table1_q5),
    .address6(exp_table1_address6),
    .ce6(exp_table1_ce6),
    .q6(exp_table1_q6),
    .address7(exp_table1_address7),
    .ce7(exp_table1_ce7),
    .q7(exp_table1_q7),
    .address8(exp_table1_address8),
    .ce8(exp_table1_ce8),
    .q8(exp_table1_q8),
    .address9(exp_table1_address9),
    .ce9(exp_table1_ce9),
    .q9(exp_table1_q9),
    .address10(exp_table1_address10),
    .ce10(exp_table1_ce10),
    .q10(exp_table1_q10),
    .address11(exp_table1_address11),
    .ce11(exp_table1_ce11),
    .q11(exp_table1_q11),
    .address12(exp_table1_address12),
    .ce12(exp_table1_ce12),
    .q12(exp_table1_q12),
    .address13(exp_table1_address13),
    .ce13(exp_table1_ce13),
    .q13(exp_table1_q13),
    .address14(exp_table1_address14),
    .ce14(exp_table1_ce14),
    .q14(exp_table1_q14),
    .address15(exp_table1_address15),
    .ce15(exp_table1_ce15),
    .q15(exp_table1_q15),
    .address16(exp_table1_address16),
    .ce16(exp_table1_ce16),
    .q16(exp_table1_q16),
    .address17(exp_table1_address17),
    .ce17(exp_table1_ce17),
    .q17(exp_table1_q17),
    .address18(exp_table1_address18),
    .ce18(exp_table1_ce18),
    .q18(exp_table1_q18)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U37(
    .din0(mul_ln1118_fu_2689_p0),
    .din1(mul_ln1118_fu_2689_p1),
    .dout(mul_ln1118_fu_2689_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U38(
    .din0(mul_ln1118_18_fu_2696_p0),
    .din1(mul_ln1118_18_fu_2696_p1),
    .dout(mul_ln1118_18_fu_2696_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U39(
    .din0(mul_ln1118_19_fu_2703_p0),
    .din1(mul_ln1118_19_fu_2703_p1),
    .dout(mul_ln1118_19_fu_2703_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U40(
    .din0(mul_ln1118_20_fu_2710_p0),
    .din1(mul_ln1118_20_fu_2710_p1),
    .dout(mul_ln1118_20_fu_2710_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U41(
    .din0(mul_ln1118_21_fu_2717_p0),
    .din1(mul_ln1118_21_fu_2717_p1),
    .dout(mul_ln1118_21_fu_2717_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U42(
    .din0(mul_ln1118_22_fu_2724_p0),
    .din1(mul_ln1118_22_fu_2724_p1),
    .dout(mul_ln1118_22_fu_2724_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U43(
    .din0(mul_ln1118_23_fu_2731_p0),
    .din1(mul_ln1118_23_fu_2731_p1),
    .dout(mul_ln1118_23_fu_2731_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U44(
    .din0(mul_ln1118_24_fu_2738_p0),
    .din1(mul_ln1118_24_fu_2738_p1),
    .dout(mul_ln1118_24_fu_2738_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U45(
    .din0(mul_ln1118_25_fu_2745_p0),
    .din1(mul_ln1118_25_fu_2745_p1),
    .dout(mul_ln1118_25_fu_2745_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U46(
    .din0(mul_ln1118_26_fu_2752_p0),
    .din1(mul_ln1118_26_fu_2752_p1),
    .dout(mul_ln1118_26_fu_2752_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U47(
    .din0(mul_ln1118_27_fu_2759_p0),
    .din1(mul_ln1118_27_fu_2759_p1),
    .dout(mul_ln1118_27_fu_2759_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U48(
    .din0(mul_ln1118_28_fu_2766_p0),
    .din1(mul_ln1118_28_fu_2766_p1),
    .dout(mul_ln1118_28_fu_2766_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U49(
    .din0(mul_ln1118_29_fu_2773_p0),
    .din1(mul_ln1118_29_fu_2773_p1),
    .dout(mul_ln1118_29_fu_2773_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U50(
    .din0(mul_ln1118_30_fu_2780_p0),
    .din1(mul_ln1118_30_fu_2780_p1),
    .dout(mul_ln1118_30_fu_2780_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U51(
    .din0(mul_ln1118_31_fu_2787_p0),
    .din1(mul_ln1118_31_fu_2787_p1),
    .dout(mul_ln1118_31_fu_2787_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U52(
    .din0(mul_ln1118_32_fu_2794_p0),
    .din1(mul_ln1118_32_fu_2794_p1),
    .dout(mul_ln1118_32_fu_2794_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U53(
    .din0(mul_ln1118_33_fu_2801_p0),
    .din1(mul_ln1118_33_fu_2801_p1),
    .dout(mul_ln1118_33_fu_2801_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U54(
    .din0(mul_ln1118_34_fu_2808_p0),
    .din1(mul_ln1118_34_fu_2808_p1),
    .dout(mul_ln1118_34_fu_2808_p2)
);

myproject_mul_mul_16s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
myproject_mul_mul_16s_16s_26_1_1_U55(
    .din0(mul_ln1118_35_fu_2815_p0),
    .din1(mul_ln1118_35_fu_2815_p1),
    .dout(mul_ln1118_35_fu_2815_p2)
);

myproject_mul_mul_7ns_16s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 23 ))
myproject_mul_mul_7ns_16s_23_1_1_U56(
    .din0(r_V_fu_2822_p0),
    .din1(kl_sum_V_fu_2638_p2),
    .dout(r_V_fu_2822_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln703_21_reg_3114 <= add_ln703_21_fu_2550_p2;
        add_ln703_25_reg_3119 <= add_ln703_25_fu_2574_p2;
        add_ln703_35_reg_3124 <= add_ln703_35_fu_2628_p2;
        log_var_0_V_read_1_reg_2919 <= log_var_0_V_read;
        log_var_10_V_read_1_reg_2869 <= log_var_10_V_read;
        log_var_11_V_read_1_reg_2864 <= log_var_11_V_read;
        log_var_12_V_read_1_reg_2859 <= log_var_12_V_read;
        log_var_13_V_read_1_reg_2854 <= log_var_13_V_read;
        log_var_14_V_read_1_reg_2849 <= log_var_14_V_read;
        log_var_15_V_read_1_reg_2844 <= log_var_15_V_read;
        log_var_16_V_read_1_reg_2839 <= log_var_16_V_read;
        log_var_17_V_read_1_reg_2834 <= log_var_17_V_read;
        log_var_18_V_read_1_reg_2829 <= log_var_18_V_read;
        log_var_1_V_read_1_reg_2914 <= log_var_1_V_read;
        log_var_2_V_read_1_reg_2909 <= log_var_2_V_read;
        log_var_3_V_read_1_reg_2904 <= log_var_3_V_read;
        log_var_4_V_read_1_reg_2899 <= log_var_4_V_read;
        log_var_5_V_read_1_reg_2894 <= log_var_5_V_read;
        log_var_6_V_read_1_reg_2889 <= log_var_6_V_read;
        log_var_7_V_read_1_reg_2884 <= log_var_7_V_read;
        log_var_8_V_read_1_reg_2879 <= log_var_8_V_read;
        log_var_9_V_read_1_reg_2874 <= log_var_9_V_read;
        trunc_ln708_10_reg_2974 <= {{mul_ln1118_27_fu_2759_p2[25:10]}};
        trunc_ln708_11_reg_2979 <= {{mul_ln1118_28_fu_2766_p2[25:10]}};
        trunc_ln708_12_reg_2984 <= {{mul_ln1118_29_fu_2773_p2[25:10]}};
        trunc_ln708_13_reg_2989 <= {{mul_ln1118_30_fu_2780_p2[25:10]}};
        trunc_ln708_14_reg_2994 <= {{mul_ln1118_31_fu_2787_p2[25:10]}};
        trunc_ln708_15_reg_2999 <= {{mul_ln1118_32_fu_2794_p2[25:10]}};
        trunc_ln708_16_reg_3004 <= {{mul_ln1118_33_fu_2801_p2[25:10]}};
        trunc_ln708_17_reg_3009 <= {{mul_ln1118_34_fu_2808_p2[25:10]}};
        trunc_ln708_18_reg_3014 <= {{mul_ln1118_35_fu_2815_p2[25:10]}};
        trunc_ln708_1_reg_2929 <= {{mul_ln1118_18_fu_2696_p2[25:10]}};
        trunc_ln708_3_reg_2939 <= {{mul_ln1118_20_fu_2710_p2[25:10]}};
        trunc_ln708_4_reg_2944 <= {{mul_ln1118_21_fu_2717_p2[25:10]}};
        trunc_ln708_5_reg_2949 <= {{mul_ln1118_22_fu_2724_p2[25:10]}};
        trunc_ln708_6_reg_2954 <= {{mul_ln1118_23_fu_2731_p2[25:10]}};
        trunc_ln708_7_reg_2959 <= {{mul_ln1118_24_fu_2738_p2[25:10]}};
        trunc_ln708_8_reg_2964 <= {{mul_ln1118_25_fu_2745_p2[25:10]}};
        trunc_ln708_9_reg_2969 <= {{mul_ln1118_26_fu_2752_p2[25:10]}};
        trunc_ln708_s_reg_2934 <= {{mul_ln1118_19_fu_2703_p2[25:10]}};
        trunc_ln_reg_2924 <= {{mul_ln1118_fu_2689_p2[25:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce0 = 1'b1;
    end else begin
        exp_table1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce1 = 1'b1;
    end else begin
        exp_table1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce10 = 1'b1;
    end else begin
        exp_table1_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce11 = 1'b1;
    end else begin
        exp_table1_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce12 = 1'b1;
    end else begin
        exp_table1_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce13 = 1'b1;
    end else begin
        exp_table1_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce14 = 1'b1;
    end else begin
        exp_table1_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce15 = 1'b1;
    end else begin
        exp_table1_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce16 = 1'b1;
    end else begin
        exp_table1_ce16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce17 = 1'b1;
    end else begin
        exp_table1_ce17 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce18 = 1'b1;
    end else begin
        exp_table1_ce18 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce2 = 1'b1;
    end else begin
        exp_table1_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce3 = 1'b1;
    end else begin
        exp_table1_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce4 = 1'b1;
    end else begin
        exp_table1_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce5 = 1'b1;
    end else begin
        exp_table1_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce6 = 1'b1;
    end else begin
        exp_table1_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce7 = 1'b1;
    end else begin
        exp_table1_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce8 = 1'b1;
    end else begin
        exp_table1_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table1_ce9 = 1'b1;
    end else begin
        exp_table1_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_V_ap_vld = 1'b1;
    end else begin
        res_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1192_10_fu_1549_p2 = ($signed(23'd524288) + $signed(sext_ln1118_35_fu_1545_p1));

assign add_ln1192_11_fu_1618_p2 = ($signed(23'd524288) + $signed(sext_ln1118_36_fu_1614_p1));

assign add_ln1192_12_fu_1687_p2 = ($signed(23'd524288) + $signed(sext_ln1118_37_fu_1683_p1));

assign add_ln1192_13_fu_1756_p2 = ($signed(23'd524288) + $signed(sext_ln1118_38_fu_1752_p1));

assign add_ln1192_14_fu_1825_p2 = ($signed(23'd524288) + $signed(sext_ln1118_39_fu_1821_p1));

assign add_ln1192_15_fu_1894_p2 = ($signed(23'd524288) + $signed(sext_ln1118_40_fu_1890_p1));

assign add_ln1192_16_fu_1963_p2 = ($signed(23'd524288) + $signed(sext_ln1118_41_fu_1959_p1));

assign add_ln1192_17_fu_2032_p2 = ($signed(23'd524288) + $signed(sext_ln1118_42_fu_2028_p1));

assign add_ln1192_18_fu_2101_p2 = ($signed(23'd524288) + $signed(sext_ln1118_43_fu_2097_p1));

assign add_ln1192_1_fu_928_p2 = ($signed(23'd524288) + $signed(sext_ln1118_26_fu_924_p1));

assign add_ln1192_2_fu_997_p2 = ($signed(23'd524288) + $signed(sext_ln1118_27_fu_993_p1));

assign add_ln1192_3_fu_1066_p2 = ($signed(23'd524288) + $signed(sext_ln1118_28_fu_1062_p1));

assign add_ln1192_4_fu_1135_p2 = ($signed(23'd524288) + $signed(sext_ln1118_29_fu_1131_p1));

assign add_ln1192_5_fu_1204_p2 = ($signed(23'd524288) + $signed(sext_ln1118_30_fu_1200_p1));

assign add_ln1192_6_fu_1273_p2 = ($signed(23'd524288) + $signed(sext_ln1118_31_fu_1269_p1));

assign add_ln1192_7_fu_1342_p2 = ($signed(23'd524288) + $signed(sext_ln1118_32_fu_1338_p1));

assign add_ln1192_8_fu_1411_p2 = ($signed(23'd524288) + $signed(sext_ln1118_33_fu_1407_p1));

assign add_ln1192_9_fu_1480_p2 = ($signed(23'd524288) + $signed(sext_ln1118_34_fu_1476_p1));

assign add_ln1192_fu_859_p2 = ($signed(23'd524288) + $signed(sext_ln1118_25_fu_855_p1));

assign add_ln1495_10_fu_1555_p2 = ($signed(22'd524288) + $signed(shl_ln1118_1_fu_1537_p3));

assign add_ln1495_11_fu_1624_p2 = ($signed(22'd524288) + $signed(shl_ln1118_10_fu_1606_p3));

assign add_ln1495_12_fu_1693_p2 = ($signed(22'd524288) + $signed(shl_ln1118_11_fu_1675_p3));

assign add_ln1495_13_fu_1762_p2 = ($signed(22'd524288) + $signed(shl_ln1118_12_fu_1744_p3));

assign add_ln1495_14_fu_1831_p2 = ($signed(22'd524288) + $signed(shl_ln1118_13_fu_1813_p3));

assign add_ln1495_15_fu_1900_p2 = ($signed(22'd524288) + $signed(shl_ln1118_14_fu_1882_p3));

assign add_ln1495_16_fu_1969_p2 = ($signed(22'd524288) + $signed(shl_ln1118_15_fu_1951_p3));

assign add_ln1495_17_fu_2038_p2 = ($signed(22'd524288) + $signed(shl_ln1118_16_fu_2020_p3));

assign add_ln1495_18_fu_2107_p2 = ($signed(22'd524288) + $signed(shl_ln1118_17_fu_2089_p3));

assign add_ln1495_1_fu_934_p2 = ($signed(22'd524288) + $signed(shl_ln1118_2_fu_916_p3));

assign add_ln1495_2_fu_1003_p2 = ($signed(22'd524288) + $signed(shl_ln1118_3_fu_985_p3));

assign add_ln1495_3_fu_1072_p2 = ($signed(22'd524288) + $signed(shl_ln1118_4_fu_1054_p3));

assign add_ln1495_4_fu_1141_p2 = ($signed(22'd524288) + $signed(shl_ln1118_5_fu_1123_p3));

assign add_ln1495_5_fu_1210_p2 = ($signed(22'd524288) + $signed(shl_ln1118_6_fu_1192_p3));

assign add_ln1495_6_fu_1279_p2 = ($signed(22'd524288) + $signed(shl_ln1118_7_fu_1261_p3));

assign add_ln1495_7_fu_1348_p2 = ($signed(22'd524288) + $signed(shl_ln1118_8_fu_1330_p3));

assign add_ln1495_8_fu_1417_p2 = ($signed(22'd524288) + $signed(shl_ln1118_9_fu_1399_p3));

assign add_ln1495_9_fu_1486_p2 = ($signed(22'd524288) + $signed(shl_ln1118_s_fu_1468_p3));

assign add_ln1495_fu_865_p2 = ($signed(22'd524288) + $signed(shl_ln_fu_847_p3));

assign add_ln703_10_fu_2208_p2 = (16'd1024 + log_var_10_V_read_1_reg_2869);

assign add_ln703_11_fu_2213_p2 = (16'd1024 + log_var_11_V_read_1_reg_2864);

assign add_ln703_12_fu_2218_p2 = (16'd1024 + log_var_12_V_read_1_reg_2859);

assign add_ln703_13_fu_2223_p2 = (16'd1024 + log_var_13_V_read_1_reg_2854);

assign add_ln703_14_fu_2228_p2 = (16'd1024 + log_var_14_V_read_1_reg_2849);

assign add_ln703_15_fu_2233_p2 = (16'd1024 + log_var_15_V_read_1_reg_2844);

assign add_ln703_16_fu_2238_p2 = (16'd1024 + log_var_16_V_read_1_reg_2839);

assign add_ln703_17_fu_2243_p2 = (16'd1024 + log_var_17_V_read_1_reg_2834);

assign add_ln703_18_fu_2248_p2 = (16'd1024 + log_var_18_V_read_1_reg_2829);

assign add_ln703_19_fu_2538_p2 = (kl_17_V_fu_2528_p2 + kl_16_V_fu_2523_p2);

assign add_ln703_1_fu_2163_p2 = (16'd1024 + log_var_1_V_read_1_reg_2914);

assign add_ln703_20_fu_2544_p2 = (kl_18_V_fu_2533_p2 + kl_0_V_fu_2443_p2);

assign add_ln703_21_fu_2550_p2 = (add_ln703_20_fu_2544_p2 + add_ln703_19_fu_2538_p2);

assign add_ln703_22_fu_2556_p2 = (kl_1_V_fu_2448_p2 + kl_2_V_fu_2453_p2);

assign add_ln703_23_fu_2562_p2 = (kl_4_V_fu_2463_p2 + kl_5_V_fu_2468_p2);

assign add_ln703_24_fu_2568_p2 = (add_ln703_23_fu_2562_p2 + kl_3_V_fu_2458_p2);

assign add_ln703_25_fu_2574_p2 = (add_ln703_24_fu_2568_p2 + add_ln703_22_fu_2556_p2);

assign add_ln703_26_fu_2634_p2 = (add_ln703_25_reg_3119 + add_ln703_21_reg_3114);

assign add_ln703_27_fu_2580_p2 = (kl_6_V_fu_2473_p2 + kl_7_V_fu_2478_p2);

assign add_ln703_28_fu_2586_p2 = (kl_9_V_fu_2488_p2 + kl_10_V_fu_2493_p2);

assign add_ln703_29_fu_2592_p2 = (add_ln703_28_fu_2586_p2 + kl_8_V_fu_2483_p2);

assign add_ln703_2_fu_2168_p2 = (16'd1024 + log_var_2_V_read_1_reg_2909);

assign add_ln703_30_fu_2598_p2 = (add_ln703_29_fu_2592_p2 + add_ln703_27_fu_2580_p2);

assign add_ln703_31_fu_2604_p2 = (kl_11_V_fu_2498_p2 + kl_12_V_fu_2503_p2);

assign add_ln703_32_fu_2610_p2 = (kl_14_V_fu_2513_p2 + kl_15_V_fu_2518_p2);

assign add_ln703_33_fu_2616_p2 = (add_ln703_32_fu_2610_p2 + kl_13_V_fu_2508_p2);

assign add_ln703_34_fu_2622_p2 = (add_ln703_33_fu_2616_p2 + add_ln703_31_fu_2604_p2);

assign add_ln703_35_fu_2628_p2 = (add_ln703_34_fu_2622_p2 + add_ln703_30_fu_2598_p2);

assign add_ln703_3_fu_2173_p2 = (16'd1024 + log_var_3_V_read_1_reg_2904);

assign add_ln703_4_fu_2178_p2 = (16'd1024 + log_var_4_V_read_1_reg_2899);

assign add_ln703_5_fu_2183_p2 = (16'd1024 + log_var_5_V_read_1_reg_2894);

assign add_ln703_6_fu_2188_p2 = (16'd1024 + log_var_6_V_read_1_reg_2889);

assign add_ln703_7_fu_2193_p2 = (16'd1024 + log_var_7_V_read_1_reg_2884);

assign add_ln703_8_fu_2198_p2 = (16'd1024 + log_var_8_V_read_1_reg_2879);

assign add_ln703_9_fu_2203_p2 = (16'd1024 + log_var_9_V_read_1_reg_2874);

assign add_ln703_fu_2158_p2 = (16'd1024 + log_var_0_V_read_1_reg_2919);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign exp_table1_address0 = zext_ln559_fu_911_p1;

assign exp_table1_address1 = zext_ln559_1_fu_980_p1;

assign exp_table1_address10 = zext_ln559_10_fu_1601_p1;

assign exp_table1_address11 = zext_ln559_11_fu_1670_p1;

assign exp_table1_address12 = zext_ln559_12_fu_1739_p1;

assign exp_table1_address13 = zext_ln559_13_fu_1808_p1;

assign exp_table1_address14 = zext_ln559_14_fu_1877_p1;

assign exp_table1_address15 = zext_ln559_15_fu_1946_p1;

assign exp_table1_address16 = zext_ln559_16_fu_2015_p1;

assign exp_table1_address17 = zext_ln559_17_fu_2084_p1;

assign exp_table1_address18 = zext_ln559_18_fu_2153_p1;

assign exp_table1_address2 = zext_ln559_2_fu_1049_p1;

assign exp_table1_address3 = zext_ln559_3_fu_1118_p1;

assign exp_table1_address4 = zext_ln559_4_fu_1187_p1;

assign exp_table1_address5 = zext_ln559_5_fu_1256_p1;

assign exp_table1_address6 = zext_ln559_6_fu_1325_p1;

assign exp_table1_address7 = zext_ln559_7_fu_1394_p1;

assign exp_table1_address8 = zext_ln559_8_fu_1463_p1;

assign exp_table1_address9 = zext_ln559_9_fu_1532_p1;

assign icmp_ln1494_10_fu_1577_p2 = ((select_ln68_10_fu_1569_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1646_p2 = ((select_ln68_11_fu_1638_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_1715_p2 = ((select_ln68_12_fu_1707_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_1784_p2 = ((select_ln68_13_fu_1776_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_1853_p2 = ((select_ln68_14_fu_1845_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_1922_p2 = ((select_ln68_15_fu_1914_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_1991_p2 = ((select_ln68_16_fu_1983_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_2060_p2 = ((select_ln68_17_fu_2052_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_2129_p2 = ((select_ln68_18_fu_2121_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_956_p2 = ((select_ln68_1_fu_948_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_1025_p2 = ((select_ln68_2_fu_1017_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_1094_p2 = ((select_ln68_3_fu_1086_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_1163_p2 = ((select_ln68_4_fu_1155_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1232_p2 = ((select_ln68_5_fu_1224_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1301_p2 = ((select_ln68_6_fu_1293_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1370_p2 = ((select_ln68_7_fu_1362_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1439_p2 = ((select_ln68_8_fu_1431_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1508_p2 = ((select_ln68_9_fu_1500_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_887_p2 = ((select_ln68_fu_879_p3 > 22'd1047552) ? 1'b1 : 1'b0);

assign kl_0_V_fu_2443_p2 = (sub_ln703_fu_2257_p2 - trunc_ln_reg_2924);

assign kl_10_V_fu_2493_p2 = (sub_ln703_10_fu_2357_p2 - trunc_ln708_10_reg_2974);

assign kl_11_V_fu_2498_p2 = (sub_ln703_11_fu_2367_p2 - trunc_ln708_11_reg_2979);

assign kl_12_V_fu_2503_p2 = (sub_ln703_12_fu_2377_p2 - trunc_ln708_12_reg_2984);

assign kl_13_V_fu_2508_p2 = (sub_ln703_13_fu_2387_p2 - trunc_ln708_13_reg_2989);

assign kl_14_V_fu_2513_p2 = (sub_ln703_14_fu_2397_p2 - trunc_ln708_14_reg_2994);

assign kl_15_V_fu_2518_p2 = (sub_ln703_15_fu_2407_p2 - trunc_ln708_15_reg_2999);

assign kl_16_V_fu_2523_p2 = (sub_ln703_16_fu_2417_p2 - trunc_ln708_16_reg_3004);

assign kl_17_V_fu_2528_p2 = (sub_ln703_17_fu_2427_p2 - trunc_ln708_17_reg_3009);

assign kl_18_V_fu_2533_p2 = (sub_ln703_18_fu_2437_p2 - trunc_ln708_18_reg_3014);

assign kl_1_V_fu_2448_p2 = (sub_ln703_1_fu_2267_p2 - trunc_ln708_1_reg_2929);

assign kl_2_V_fu_2453_p2 = (sub_ln703_2_fu_2277_p2 - trunc_ln708_s_reg_2934);

assign kl_3_V_fu_2458_p2 = (sub_ln703_3_fu_2287_p2 - trunc_ln708_3_reg_2939);

assign kl_4_V_fu_2463_p2 = (sub_ln703_4_fu_2297_p2 - trunc_ln708_4_reg_2944);

assign kl_5_V_fu_2468_p2 = (sub_ln703_5_fu_2307_p2 - trunc_ln708_5_reg_2949);

assign kl_6_V_fu_2473_p2 = (sub_ln703_6_fu_2317_p2 - trunc_ln708_6_reg_2954);

assign kl_7_V_fu_2478_p2 = (sub_ln703_7_fu_2327_p2 - trunc_ln708_7_reg_2959);

assign kl_8_V_fu_2483_p2 = (sub_ln703_8_fu_2337_p2 - trunc_ln708_8_reg_2964);

assign kl_9_V_fu_2488_p2 = (sub_ln703_9_fu_2347_p2 - trunc_ln708_9_reg_2969);

assign kl_sum_V_fu_2638_p2 = (add_ln703_35_reg_3124 + add_ln703_26_fu_2634_p2);

assign mul_ln1118_18_fu_2696_p0 = sext_ln1118_7_fu_613_p1;

assign mul_ln1118_18_fu_2696_p1 = sext_ln1118_7_fu_613_p1;

assign mul_ln1118_19_fu_2703_p0 = sext_ln1118_8_fu_626_p1;

assign mul_ln1118_19_fu_2703_p1 = sext_ln1118_8_fu_626_p1;

assign mul_ln1118_20_fu_2710_p0 = sext_ln1118_9_fu_639_p1;

assign mul_ln1118_20_fu_2710_p1 = sext_ln1118_9_fu_639_p1;

assign mul_ln1118_21_fu_2717_p0 = sext_ln1118_10_fu_652_p1;

assign mul_ln1118_21_fu_2717_p1 = sext_ln1118_10_fu_652_p1;

assign mul_ln1118_22_fu_2724_p0 = sext_ln1118_11_fu_665_p1;

assign mul_ln1118_22_fu_2724_p1 = sext_ln1118_11_fu_665_p1;

assign mul_ln1118_23_fu_2731_p0 = sext_ln1118_12_fu_678_p1;

assign mul_ln1118_23_fu_2731_p1 = sext_ln1118_12_fu_678_p1;

assign mul_ln1118_24_fu_2738_p0 = sext_ln1118_13_fu_691_p1;

assign mul_ln1118_24_fu_2738_p1 = sext_ln1118_13_fu_691_p1;

assign mul_ln1118_25_fu_2745_p0 = sext_ln1118_14_fu_704_p1;

assign mul_ln1118_25_fu_2745_p1 = sext_ln1118_14_fu_704_p1;

assign mul_ln1118_26_fu_2752_p0 = sext_ln1118_15_fu_717_p1;

assign mul_ln1118_26_fu_2752_p1 = sext_ln1118_15_fu_717_p1;

assign mul_ln1118_27_fu_2759_p0 = sext_ln1118_16_fu_730_p1;

assign mul_ln1118_27_fu_2759_p1 = sext_ln1118_16_fu_730_p1;

assign mul_ln1118_28_fu_2766_p0 = sext_ln1118_17_fu_743_p1;

assign mul_ln1118_28_fu_2766_p1 = sext_ln1118_17_fu_743_p1;

assign mul_ln1118_29_fu_2773_p0 = sext_ln1118_18_fu_756_p1;

assign mul_ln1118_29_fu_2773_p1 = sext_ln1118_18_fu_756_p1;

assign mul_ln1118_30_fu_2780_p0 = sext_ln1118_19_fu_769_p1;

assign mul_ln1118_30_fu_2780_p1 = sext_ln1118_19_fu_769_p1;

assign mul_ln1118_31_fu_2787_p0 = sext_ln1118_20_fu_782_p1;

assign mul_ln1118_31_fu_2787_p1 = sext_ln1118_20_fu_782_p1;

assign mul_ln1118_32_fu_2794_p0 = sext_ln1118_21_fu_795_p1;

assign mul_ln1118_32_fu_2794_p1 = sext_ln1118_21_fu_795_p1;

assign mul_ln1118_33_fu_2801_p0 = sext_ln1118_22_fu_808_p1;

assign mul_ln1118_33_fu_2801_p1 = sext_ln1118_22_fu_808_p1;

assign mul_ln1118_34_fu_2808_p0 = sext_ln1118_23_fu_821_p1;

assign mul_ln1118_34_fu_2808_p1 = sext_ln1118_23_fu_821_p1;

assign mul_ln1118_35_fu_2815_p0 = sext_ln1118_24_fu_834_p1;

assign mul_ln1118_35_fu_2815_p1 = sext_ln1118_24_fu_834_p1;

assign mul_ln1118_fu_2689_p0 = sext_ln1118_fu_600_p1;

assign mul_ln1118_fu_2689_p1 = sext_ln1118_fu_600_p1;

assign r_V_1_fu_2668_p2 = ($signed(23'd0) - $signed(sext_ln1118_44_fu_2664_p1));

assign r_V_fu_2822_p0 = 23'd53;

assign res_V = $signed(tmp_38_fu_2674_p4);

assign select_ln68_10_fu_1569_p3 = ((tmp_29_fu_1561_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_10_fu_1555_p2);

assign select_ln68_11_fu_1638_p3 = ((tmp_30_fu_1630_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_11_fu_1624_p2);

assign select_ln68_12_fu_1707_p3 = ((tmp_31_fu_1699_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_12_fu_1693_p2);

assign select_ln68_13_fu_1776_p3 = ((tmp_32_fu_1768_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_13_fu_1762_p2);

assign select_ln68_14_fu_1845_p3 = ((tmp_33_fu_1837_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_14_fu_1831_p2);

assign select_ln68_15_fu_1914_p3 = ((tmp_34_fu_1906_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_15_fu_1900_p2);

assign select_ln68_16_fu_1983_p3 = ((tmp_35_fu_1975_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_16_fu_1969_p2);

assign select_ln68_17_fu_2052_p3 = ((tmp_36_fu_2044_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_17_fu_2038_p2);

assign select_ln68_18_fu_2121_p3 = ((tmp_37_fu_2113_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_18_fu_2107_p2);

assign select_ln68_1_fu_948_p3 = ((tmp_20_fu_940_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_1_fu_934_p2);

assign select_ln68_2_fu_1017_p3 = ((tmp_21_fu_1009_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_2_fu_1003_p2);

assign select_ln68_3_fu_1086_p3 = ((tmp_22_fu_1078_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_3_fu_1072_p2);

assign select_ln68_4_fu_1155_p3 = ((tmp_23_fu_1147_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_4_fu_1141_p2);

assign select_ln68_5_fu_1224_p3 = ((tmp_24_fu_1216_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_5_fu_1210_p2);

assign select_ln68_6_fu_1293_p3 = ((tmp_25_fu_1285_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_6_fu_1279_p2);

assign select_ln68_7_fu_1362_p3 = ((tmp_26_fu_1354_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_7_fu_1348_p2);

assign select_ln68_8_fu_1431_p3 = ((tmp_27_fu_1423_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_8_fu_1417_p2);

assign select_ln68_9_fu_1500_p3 = ((tmp_28_fu_1492_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_9_fu_1486_p2);

assign select_ln68_fu_879_p3 = ((tmp_19_fu_871_p3[0:0] === 1'b1) ? 22'd0 : add_ln1495_fu_865_p2);

assign select_ln70_10_fu_1593_p3 = ((icmp_ln1494_10_fu_1577_p2[0:0] === 1'b1) ? 12'd1023 : tmp_s_fu_1583_p4);

assign select_ln70_11_fu_1662_p3 = ((icmp_ln1494_11_fu_1646_p2[0:0] === 1'b1) ? 12'd1023 : tmp_10_fu_1652_p4);

assign select_ln70_12_fu_1731_p3 = ((icmp_ln1494_12_fu_1715_p2[0:0] === 1'b1) ? 12'd1023 : tmp_11_fu_1721_p4);

assign select_ln70_13_fu_1800_p3 = ((icmp_ln1494_13_fu_1784_p2[0:0] === 1'b1) ? 12'd1023 : tmp_12_fu_1790_p4);

assign select_ln70_14_fu_1869_p3 = ((icmp_ln1494_14_fu_1853_p2[0:0] === 1'b1) ? 12'd1023 : tmp_13_fu_1859_p4);

assign select_ln70_15_fu_1938_p3 = ((icmp_ln1494_15_fu_1922_p2[0:0] === 1'b1) ? 12'd1023 : tmp_14_fu_1928_p4);

assign select_ln70_16_fu_2007_p3 = ((icmp_ln1494_16_fu_1991_p2[0:0] === 1'b1) ? 12'd1023 : tmp_15_fu_1997_p4);

assign select_ln70_17_fu_2076_p3 = ((icmp_ln1494_17_fu_2060_p2[0:0] === 1'b1) ? 12'd1023 : tmp_16_fu_2066_p4);

assign select_ln70_18_fu_2145_p3 = ((icmp_ln1494_18_fu_2129_p2[0:0] === 1'b1) ? 12'd1023 : tmp_17_fu_2135_p4);

assign select_ln70_1_fu_972_p3 = ((icmp_ln1494_1_fu_956_p2[0:0] === 1'b1) ? 12'd1023 : tmp_1_fu_962_p4);

assign select_ln70_2_fu_1041_p3 = ((icmp_ln1494_2_fu_1025_p2[0:0] === 1'b1) ? 12'd1023 : tmp_2_fu_1031_p4);

assign select_ln70_3_fu_1110_p3 = ((icmp_ln1494_3_fu_1094_p2[0:0] === 1'b1) ? 12'd1023 : tmp_3_fu_1100_p4);

assign select_ln70_4_fu_1179_p3 = ((icmp_ln1494_4_fu_1163_p2[0:0] === 1'b1) ? 12'd1023 : tmp_4_fu_1169_p4);

assign select_ln70_5_fu_1248_p3 = ((icmp_ln1494_5_fu_1232_p2[0:0] === 1'b1) ? 12'd1023 : tmp_5_fu_1238_p4);

assign select_ln70_6_fu_1317_p3 = ((icmp_ln1494_6_fu_1301_p2[0:0] === 1'b1) ? 12'd1023 : tmp_6_fu_1307_p4);

assign select_ln70_7_fu_1386_p3 = ((icmp_ln1494_7_fu_1370_p2[0:0] === 1'b1) ? 12'd1023 : tmp_7_fu_1376_p4);

assign select_ln70_8_fu_1455_p3 = ((icmp_ln1494_8_fu_1439_p2[0:0] === 1'b1) ? 12'd1023 : tmp_8_fu_1445_p4);

assign select_ln70_9_fu_1524_p3 = ((icmp_ln1494_9_fu_1508_p2[0:0] === 1'b1) ? 12'd1023 : tmp_9_fu_1514_p4);

assign select_ln70_fu_903_p3 = ((icmp_ln1494_fu_887_p2[0:0] === 1'b1) ? 12'd1023 : tmp_fu_893_p4);

assign sext_ln1118_10_fu_652_p1 = $signed(mean_4_V_read);

assign sext_ln1118_11_fu_665_p1 = $signed(mean_5_V_read);

assign sext_ln1118_12_fu_678_p1 = $signed(mean_6_V_read);

assign sext_ln1118_13_fu_691_p1 = $signed(mean_7_V_read);

assign sext_ln1118_14_fu_704_p1 = $signed(mean_8_V_read);

assign sext_ln1118_15_fu_717_p1 = $signed(mean_9_V_read);

assign sext_ln1118_16_fu_730_p1 = $signed(mean_10_V_read);

assign sext_ln1118_17_fu_743_p1 = $signed(mean_11_V_read);

assign sext_ln1118_18_fu_756_p1 = $signed(mean_12_V_read);

assign sext_ln1118_19_fu_769_p1 = $signed(mean_13_V_read);

assign sext_ln1118_20_fu_782_p1 = $signed(mean_14_V_read);

assign sext_ln1118_21_fu_795_p1 = $signed(mean_15_V_read);

assign sext_ln1118_22_fu_808_p1 = $signed(mean_16_V_read);

assign sext_ln1118_23_fu_821_p1 = $signed(mean_17_V_read);

assign sext_ln1118_24_fu_834_p1 = $signed(mean_18_V_read);

assign sext_ln1118_25_fu_855_p1 = shl_ln_fu_847_p3;

assign sext_ln1118_26_fu_924_p1 = shl_ln1118_2_fu_916_p3;

assign sext_ln1118_27_fu_993_p1 = shl_ln1118_3_fu_985_p3;

assign sext_ln1118_28_fu_1062_p1 = shl_ln1118_4_fu_1054_p3;

assign sext_ln1118_29_fu_1131_p1 = shl_ln1118_5_fu_1123_p3;

assign sext_ln1118_30_fu_1200_p1 = shl_ln1118_6_fu_1192_p3;

assign sext_ln1118_31_fu_1269_p1 = shl_ln1118_7_fu_1261_p3;

assign sext_ln1118_32_fu_1338_p1 = shl_ln1118_8_fu_1330_p3;

assign sext_ln1118_33_fu_1407_p1 = shl_ln1118_9_fu_1399_p3;

assign sext_ln1118_34_fu_1476_p1 = shl_ln1118_s_fu_1468_p3;

assign sext_ln1118_35_fu_1545_p1 = shl_ln1118_1_fu_1537_p3;

assign sext_ln1118_36_fu_1614_p1 = shl_ln1118_10_fu_1606_p3;

assign sext_ln1118_37_fu_1683_p1 = shl_ln1118_11_fu_1675_p3;

assign sext_ln1118_38_fu_1752_p1 = shl_ln1118_12_fu_1744_p3;

assign sext_ln1118_39_fu_1821_p1 = shl_ln1118_13_fu_1813_p3;

assign sext_ln1118_40_fu_1890_p1 = shl_ln1118_14_fu_1882_p3;

assign sext_ln1118_41_fu_1959_p1 = shl_ln1118_15_fu_1951_p3;

assign sext_ln1118_42_fu_2028_p1 = shl_ln1118_16_fu_2020_p3;

assign sext_ln1118_43_fu_2097_p1 = shl_ln1118_17_fu_2089_p3;

assign sext_ln1118_44_fu_2664_p1 = $signed(tmp_18_fu_2656_p3);

assign sext_ln1118_7_fu_613_p1 = $signed(mean_1_V_read);

assign sext_ln1118_8_fu_626_p1 = $signed(mean_2_V_read);

assign sext_ln1118_9_fu_639_p1 = $signed(mean_3_V_read);

assign sext_ln1118_fu_600_p1 = $signed(mean_0_V_read);

assign shl_ln1118_10_fu_1606_p3 = {{log_var_11_V_read}, {6'd0}};

assign shl_ln1118_11_fu_1675_p3 = {{log_var_12_V_read}, {6'd0}};

assign shl_ln1118_12_fu_1744_p3 = {{log_var_13_V_read}, {6'd0}};

assign shl_ln1118_13_fu_1813_p3 = {{log_var_14_V_read}, {6'd0}};

assign shl_ln1118_14_fu_1882_p3 = {{log_var_15_V_read}, {6'd0}};

assign shl_ln1118_15_fu_1951_p3 = {{log_var_16_V_read}, {6'd0}};

assign shl_ln1118_16_fu_2020_p3 = {{log_var_17_V_read}, {6'd0}};

assign shl_ln1118_17_fu_2089_p3 = {{log_var_18_V_read}, {6'd0}};

assign shl_ln1118_1_fu_1537_p3 = {{log_var_10_V_read}, {6'd0}};

assign shl_ln1118_2_fu_916_p3 = {{log_var_1_V_read}, {6'd0}};

assign shl_ln1118_3_fu_985_p3 = {{log_var_2_V_read}, {6'd0}};

assign shl_ln1118_4_fu_1054_p3 = {{log_var_3_V_read}, {6'd0}};

assign shl_ln1118_5_fu_1123_p3 = {{log_var_4_V_read}, {6'd0}};

assign shl_ln1118_6_fu_1192_p3 = {{log_var_5_V_read}, {6'd0}};

assign shl_ln1118_7_fu_1261_p3 = {{log_var_6_V_read}, {6'd0}};

assign shl_ln1118_8_fu_1330_p3 = {{log_var_7_V_read}, {6'd0}};

assign shl_ln1118_9_fu_1399_p3 = {{log_var_8_V_read}, {6'd0}};

assign shl_ln1118_s_fu_1468_p3 = {{log_var_9_V_read}, {6'd0}};

assign shl_ln_fu_847_p3 = {{log_var_0_V_read}, {6'd0}};

assign sub_ln703_10_fu_2357_p2 = (add_ln703_10_fu_2208_p2 - trunc_ln1193_10_fu_2353_p1);

assign sub_ln703_11_fu_2367_p2 = (add_ln703_11_fu_2213_p2 - trunc_ln1193_11_fu_2363_p1);

assign sub_ln703_12_fu_2377_p2 = (add_ln703_12_fu_2218_p2 - trunc_ln1193_12_fu_2373_p1);

assign sub_ln703_13_fu_2387_p2 = (add_ln703_13_fu_2223_p2 - trunc_ln1193_13_fu_2383_p1);

assign sub_ln703_14_fu_2397_p2 = (add_ln703_14_fu_2228_p2 - trunc_ln1193_14_fu_2393_p1);

assign sub_ln703_15_fu_2407_p2 = (add_ln703_15_fu_2233_p2 - trunc_ln1193_15_fu_2403_p1);

assign sub_ln703_16_fu_2417_p2 = (add_ln703_16_fu_2238_p2 - trunc_ln1193_16_fu_2413_p1);

assign sub_ln703_17_fu_2427_p2 = (add_ln703_17_fu_2243_p2 - trunc_ln1193_17_fu_2423_p1);

assign sub_ln703_18_fu_2437_p2 = (add_ln703_18_fu_2248_p2 - trunc_ln1193_18_fu_2433_p1);

assign sub_ln703_1_fu_2267_p2 = (add_ln703_1_fu_2163_p2 - trunc_ln1193_1_fu_2263_p1);

assign sub_ln703_2_fu_2277_p2 = (add_ln703_2_fu_2168_p2 - trunc_ln1193_2_fu_2273_p1);

assign sub_ln703_3_fu_2287_p2 = (add_ln703_3_fu_2173_p2 - trunc_ln1193_3_fu_2283_p1);

assign sub_ln703_4_fu_2297_p2 = (add_ln703_4_fu_2178_p2 - trunc_ln1193_4_fu_2293_p1);

assign sub_ln703_5_fu_2307_p2 = (add_ln703_5_fu_2183_p2 - trunc_ln1193_5_fu_2303_p1);

assign sub_ln703_6_fu_2317_p2 = (add_ln703_6_fu_2188_p2 - trunc_ln1193_6_fu_2313_p1);

assign sub_ln703_7_fu_2327_p2 = (add_ln703_7_fu_2193_p2 - trunc_ln1193_7_fu_2323_p1);

assign sub_ln703_8_fu_2337_p2 = (add_ln703_8_fu_2198_p2 - trunc_ln1193_8_fu_2333_p1);

assign sub_ln703_9_fu_2347_p2 = (add_ln703_9_fu_2203_p2 - trunc_ln1193_9_fu_2343_p1);

assign sub_ln703_fu_2257_p2 = (add_ln703_fu_2158_p2 - trunc_ln1193_fu_2253_p1);

assign tmp_10_fu_1652_p4 = {{select_ln68_11_fu_1638_p3[21:10]}};

assign tmp_11_fu_1721_p4 = {{select_ln68_12_fu_1707_p3[21:10]}};

assign tmp_12_fu_1790_p4 = {{select_ln68_13_fu_1776_p3[21:10]}};

assign tmp_13_fu_1859_p4 = {{select_ln68_14_fu_1845_p3[21:10]}};

assign tmp_14_fu_1928_p4 = {{select_ln68_15_fu_1914_p3[21:10]}};

assign tmp_15_fu_1997_p4 = {{select_ln68_16_fu_1983_p3[21:10]}};

assign tmp_16_fu_2066_p4 = {{select_ln68_17_fu_2052_p3[21:10]}};

assign tmp_17_fu_2135_p4 = {{select_ln68_18_fu_2121_p3[21:10]}};

assign tmp_18_fu_2656_p3 = {{trunc_ln708_19_fu_2647_p4}, {9'd0}};

assign tmp_19_fu_871_p3 = add_ln1192_fu_859_p2[32'd22];

assign tmp_1_fu_962_p4 = {{select_ln68_1_fu_948_p3[21:10]}};

assign tmp_20_fu_940_p3 = add_ln1192_1_fu_928_p2[32'd22];

assign tmp_21_fu_1009_p3 = add_ln1192_2_fu_997_p2[32'd22];

assign tmp_22_fu_1078_p3 = add_ln1192_3_fu_1066_p2[32'd22];

assign tmp_23_fu_1147_p3 = add_ln1192_4_fu_1135_p2[32'd22];

assign tmp_24_fu_1216_p3 = add_ln1192_5_fu_1204_p2[32'd22];

assign tmp_25_fu_1285_p3 = add_ln1192_6_fu_1273_p2[32'd22];

assign tmp_26_fu_1354_p3 = add_ln1192_7_fu_1342_p2[32'd22];

assign tmp_27_fu_1423_p3 = add_ln1192_8_fu_1411_p2[32'd22];

assign tmp_28_fu_1492_p3 = add_ln1192_9_fu_1480_p2[32'd22];

assign tmp_29_fu_1561_p3 = add_ln1192_10_fu_1549_p2[32'd22];

assign tmp_2_fu_1031_p4 = {{select_ln68_2_fu_1017_p3[21:10]}};

assign tmp_30_fu_1630_p3 = add_ln1192_11_fu_1618_p2[32'd22];

assign tmp_31_fu_1699_p3 = add_ln1192_12_fu_1687_p2[32'd22];

assign tmp_32_fu_1768_p3 = add_ln1192_13_fu_1756_p2[32'd22];

assign tmp_33_fu_1837_p3 = add_ln1192_14_fu_1825_p2[32'd22];

assign tmp_34_fu_1906_p3 = add_ln1192_15_fu_1894_p2[32'd22];

assign tmp_35_fu_1975_p3 = add_ln1192_16_fu_1963_p2[32'd22];

assign tmp_36_fu_2044_p3 = add_ln1192_17_fu_2032_p2[32'd22];

assign tmp_37_fu_2113_p3 = add_ln1192_18_fu_2101_p2[32'd22];

assign tmp_38_fu_2674_p4 = {{r_V_1_fu_2668_p2[22:10]}};

assign tmp_3_fu_1100_p4 = {{select_ln68_3_fu_1086_p3[21:10]}};

assign tmp_4_fu_1169_p4 = {{select_ln68_4_fu_1155_p3[21:10]}};

assign tmp_5_fu_1238_p4 = {{select_ln68_5_fu_1224_p3[21:10]}};

assign tmp_6_fu_1307_p4 = {{select_ln68_6_fu_1293_p3[21:10]}};

assign tmp_7_fu_1376_p4 = {{select_ln68_7_fu_1362_p3[21:10]}};

assign tmp_8_fu_1445_p4 = {{select_ln68_8_fu_1431_p3[21:10]}};

assign tmp_9_fu_1514_p4 = {{select_ln68_9_fu_1500_p3[21:10]}};

assign tmp_fu_893_p4 = {{select_ln68_fu_879_p3[21:10]}};

assign tmp_s_fu_1583_p4 = {{select_ln68_10_fu_1569_p3[21:10]}};

assign trunc_ln1193_10_fu_2353_p1 = exp_table1_q10[15:0];

assign trunc_ln1193_11_fu_2363_p1 = exp_table1_q11[15:0];

assign trunc_ln1193_12_fu_2373_p1 = exp_table1_q12[15:0];

assign trunc_ln1193_13_fu_2383_p1 = exp_table1_q13[15:0];

assign trunc_ln1193_14_fu_2393_p1 = exp_table1_q14[15:0];

assign trunc_ln1193_15_fu_2403_p1 = exp_table1_q15[15:0];

assign trunc_ln1193_16_fu_2413_p1 = exp_table1_q16[15:0];

assign trunc_ln1193_17_fu_2423_p1 = exp_table1_q17[15:0];

assign trunc_ln1193_18_fu_2433_p1 = exp_table1_q18[15:0];

assign trunc_ln1193_1_fu_2263_p1 = exp_table1_q1[15:0];

assign trunc_ln1193_2_fu_2273_p1 = exp_table1_q2[15:0];

assign trunc_ln1193_3_fu_2283_p1 = exp_table1_q3[15:0];

assign trunc_ln1193_4_fu_2293_p1 = exp_table1_q4[15:0];

assign trunc_ln1193_5_fu_2303_p1 = exp_table1_q5[15:0];

assign trunc_ln1193_6_fu_2313_p1 = exp_table1_q6[15:0];

assign trunc_ln1193_7_fu_2323_p1 = exp_table1_q7[15:0];

assign trunc_ln1193_8_fu_2333_p1 = exp_table1_q8[15:0];

assign trunc_ln1193_9_fu_2343_p1 = exp_table1_q9[15:0];

assign trunc_ln1193_fu_2253_p1 = exp_table1_q0[15:0];

assign trunc_ln708_19_fu_2647_p4 = {{r_V_fu_2822_p2[22:10]}};

assign zext_ln559_10_fu_1601_p1 = select_ln70_10_fu_1593_p3;

assign zext_ln559_11_fu_1670_p1 = select_ln70_11_fu_1662_p3;

assign zext_ln559_12_fu_1739_p1 = select_ln70_12_fu_1731_p3;

assign zext_ln559_13_fu_1808_p1 = select_ln70_13_fu_1800_p3;

assign zext_ln559_14_fu_1877_p1 = select_ln70_14_fu_1869_p3;

assign zext_ln559_15_fu_1946_p1 = select_ln70_15_fu_1938_p3;

assign zext_ln559_16_fu_2015_p1 = select_ln70_16_fu_2007_p3;

assign zext_ln559_17_fu_2084_p1 = select_ln70_17_fu_2076_p3;

assign zext_ln559_18_fu_2153_p1 = select_ln70_18_fu_2145_p3;

assign zext_ln559_1_fu_980_p1 = select_ln70_1_fu_972_p3;

assign zext_ln559_2_fu_1049_p1 = select_ln70_2_fu_1041_p3;

assign zext_ln559_3_fu_1118_p1 = select_ln70_3_fu_1110_p3;

assign zext_ln559_4_fu_1187_p1 = select_ln70_4_fu_1179_p3;

assign zext_ln559_5_fu_1256_p1 = select_ln70_5_fu_1248_p3;

assign zext_ln559_6_fu_1325_p1 = select_ln70_6_fu_1317_p3;

assign zext_ln559_7_fu_1394_p1 = select_ln70_7_fu_1386_p3;

assign zext_ln559_8_fu_1463_p1 = select_ln70_8_fu_1455_p3;

assign zext_ln559_9_fu_1532_p1 = select_ln70_9_fu_1524_p3;

assign zext_ln559_fu_911_p1 = select_ln70_fu_903_p3;

endmodule //klloss_ap_fixed_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
